#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hooks for grow-with-freya..."

# Change to grow-with-freya directory and run lint-staged
cd grow-with-freya && npm run pre-commit
