// Generated by gpt-image-generator-browser (export-for-app). Do not edit by hand:
// re-run the export to change it. Assets live in assets/stories/hold-on-juni/.
import { Story } from '@/types/story';

export const holdOnJuni: Story = {
    "id": "hold-on-juni",
    "title": "Hold On, Juni",
    "localizedTitle": {
      "en": "Hold On, Juni",
    },
    "category": "growing",
    "description": "Juni used to ride on Papa's tummy every evening, but now baby Bean sleeps there. When the water starts to pull, Juni learns that love can change shape: from being carried to holding on, side by side.",
    "ageRange": "2-4",
    "author": "Early Roots",
    "tags": [
      "emotions",
      "animals",
      "interactive",
      "bedtime",
    ],
    "isAvailable": true,
    "isFree": false,
    "isPremium": true,
    "duration": 5,
    "coverImage": require('../../assets/stories/hold-on-juni/cover/thumbnail.webp'),
    "pages": [
      {
        "id": "hold-on-juni-cover",
        "pageNumber": 0,
        "type": "cover",
        "text": "Hold On, Juni",
        "backgroundImage": require('../../assets/stories/hold-on-juni/cover/cover.webp'),
      },
      {
        "id": "hold-on-juni-1",
        "pageNumber": 1,
        "type": "story",
        "text": "When Juni was a little otter, she rode on Papa's tummy as he floated in the bay. Juni is now getting older and bigger.\n\u201cYou are heavy now Juni,\u201d said Papa, \u201cI think it is time you start swimming more\u201d",
        "localizedText": {
          "2-4": {
            "en": "When Juni was a little otter, she rode on Papa's tummy as he floated in the bay. Juni is now getting older and bigger.\n\u201cYou are heavy now Juni,\u201d said Papa, \u201cI think it is time you start swimming more\u201d",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-1/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-2",
        "pageNumber": 2,
        "type": "story",
        "text": "Juni has a tiny little brother called Bean, who also likes to fall asleep on Papa's tummy. Juni's started to feel sad as she is getting too big for Papa and knows it is time to swim more.",
        "localizedText": {
          "2-4": {
            "en": "Juni has a tiny little brother called Bean, who also likes to fall asleep on Papa's tummy. Juni's started to feel sad as she is getting too big for Papa and knows it is time to swim more.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-2/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-3",
        "pageNumber": 3,
        "type": "story",
        "text": "Whilst Bean sleeps, Juni feels sad that she can no longer fit on Papa's belly and goes to her cosy spot on a rock. She comes across a speckled shell. Juni wonders what's underneath.",
        "localizedText": {
          "2-4": {
            "en": "Whilst Bean sleeps, Juni feels sad that she can no longer fit on Papa's belly and goes to her cosy spot on a rock. She comes across a speckled shell. Juni wonders what's underneath.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-3/background.webp'),
        "interactionType": "interactive_state_change",
        "interactiveElements": [
          {
            "id": "speckled-clam-shell",
            "type": "reveal",
            "image": require('../../assets/stories/hold-on-juni/page-3/props/speckled-clam-shell-open.webp'),
            "position": {
              "x": 0.3722375690607735,
              "y": 0.5128913443830571,
            },
            "size": {
              "width": 0.162292817679558,
              "height": 0.1869244935543278,
            },
            "hitArea": {
              "x": 0.37232,
              "y": 0.51368,
              "width": 0.12768,
              "height": 0.18544,
            },
          },
        ],
      },
      {
        "id": "hold-on-juni-4",
        "pageNumber": 4,
        "type": "story",
        "text": "Juni swam and begun learning how to be an independent swimmer where she came across her friend Fish.\n\u201cI'm too big for Papa's tummy,\u201d she told Fish.\n\u201cToo big for everything.\u201d\n\nFish replies \"You get bigger as you get older, but now you can swim further - come, follow me!\".",
        "localizedText": {
          "2-4": {
            "en": "Juni swam and begun learning how to be an independent swimmer where she came across her friend Fish.\n\u201cI'm too big for Papa's tummy,\u201d she told Fish.\n\u201cToo big for everything.\u201d\n\nFish replies \"You get bigger as you get older, but now you can swim further - come, follow me!\".",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-4/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-5",
        "pageNumber": 5,
        "type": "story",
        "text": "Fish swam into the distance and Juni followed. Juni starts to feel scared and floats back and tries to grab the kelp to help her climb onto land. The water began to pull as she grasped the kelp, then Juni's paws slipped off and she started to drift.",
        "localizedText": {
          "2-4": {
            "en": "Fish swam into the distance and Juni followed. Juni starts to feel scared and floats back and tries to grab the kelp to help her climb onto land. The water began to pull as she grasped the kelp, then Juni's paws slipped off and she started to drift.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-5/background.webp'),
        "interactionType": "interactive_state_change",
        "interactiveElements": [
          {
            "id": "long-kelp-strand",
            "type": "reveal",
            "image": require('../../assets/stories/hold-on-juni/page-5/props/long-kelp-strand-open.webp'),
            "position": {
              "x": 0.0462707182320442,
              "y": 0.39134438305709024,
            },
            "size": {
              "width": 0.43232044198895025,
              "height": 0.2440147329650092,
            },
            "hitArea": {
              "x": 0.12,
              "y": 0.392175,
              "width": 0.358245,
              "height": 0.242345,
            },
          },
        ],
      },
      {
        "id": "hold-on-juni-6",
        "pageNumber": 6,
        "type": "story",
        "text": "Papa saw from afar.\nHe wrapped Bean in kelp, snug and safe,\nand swam as fast as he could to help.",
        "localizedText": {
          "2-4": {
            "en": "Papa saw from afar.\nHe wrapped Bean in kelp, snug and safe,\nand swam as fast as he could to help.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-6/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-7",
        "pageNumber": 7,
        "type": "story",
        "text": "Papa reaches Juni and gives her kelp to wrap herself in.\nHe floated right beside her and held out his paw.\n\u201cHold on,\u201d he said. \"You should not try and swim in the deeper water until you are comfortable in the shallow end\".",
        "localizedText": {
          "2-4": {
            "en": "Papa reaches Juni and gives her kelp to wrap herself in.\nHe floated right beside her and held out his paw.\n\u201cHold on,\u201d he said. \"You should not try and swim in the deeper water until you are comfortable in the shallow end\".",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-7/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-8",
        "pageNumber": 8,
        "type": "story",
        "text": "Juni reached out.\nPaw in paw, they floated side by side,\nand the water couldn't pull them apart. Juni felt safe to let go and to swim by herself again, whilst Papa watched.\n\n\"Well done, you are doing it!\" says Papa.",
        "localizedText": {
          "2-4": {
            "en": "Juni reached out.\nPaw in paw, they floated side by side,\nand the water couldn't pull them apart. Juni felt safe to let go and to swim by herself again, whilst Papa watched.\n\n\"Well done, you are doing it!\" says Papa.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-8/background.webp'),
        "interactionType": "interactive_state_change",
        "interactiveElements": [
          {
            "id": "juni-s-and-papa-s-reaching-paws",
            "type": "reveal",
            "image": require('../../assets/stories/hold-on-juni/page-8/props/juni-s-and-papa-s-reaching-paws-open.webp'),
            "position": {
              "x": 0.31629834254143646,
              "y": 0.39226519337016574,
            },
            "size": {
              "width": 0.1712707182320442,
              "height": 0.13075506445672191,
            },
            "hitArea": {
              "x": 0.31696,
              "y": 0.39256,
              "width": 0.16992,
              "height": 0.12968,
            },
          },
        ],
      },
      {
        "id": "hold-on-juni-9",
        "pageNumber": 9,
        "type": "story",
        "text": "Back by the rocks, Bean was waking up,\nJuni swam straight to Bean. Juni realised as she got bigger, she also became a better swimmer and could float on tougher water. Juni however, needs Papa's tummy to stay safe as he is not quite ready to swim yet.",
        "localizedText": {
          "2-4": {
            "en": "Back by the rocks, Bean was waking up,\nJuni swam straight to Bean. Juni realised as she got bigger, she also became a better swimmer and could float on tougher water. Juni however, needs Papa's tummy to stay safe as he is not quite ready to swim yet.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-9/background.webp'),
        "interactionType": "none",
      },
      {
        "id": "hold-on-juni-10",
        "pageNumber": 10,
        "type": "story",
        "text": "That night they floated in a row under the moon.\nJuni held Papa's paw, and Bean's.\n\u201cHold on,\u201d said Juni. \u201cSo we don't drift apart.\u201d\n\nJuni was happy that despite being too big for Papa's tummy, she could swim stronger and explore the world, she just needed more confidence in herself and should learn safely.",
        "localizedText": {
          "2-4": {
            "en": "That night they floated in a row under the moon.\nJuni held Papa's paw, and Bean's.\n\u201cHold on,\u201d said Juni. \u201cSo we don't drift apart.\u201d\n\nJuni was happy that despite being too big for Papa's tummy, she could swim stronger and explore the world, she just needed more confidence in herself and should learn safely.",
          },
        },
        "backgroundImage": require('../../assets/stories/hold-on-juni/page-10/background.webp'),
        "interactionType": "none",
      },
    ],
  };
