// Generated by gpt-image-generator-browser (export-for-app). Do not edit by hand.
import { Story } from '@/types/story';
import { holdOnJuni } from './hold-on-juni';
import { myTurnToDing } from './my-turn-to-ding';

/** Books built by the story factory and bundled into the app. */
export const GENERATED_STORIES: Story[] = [
  holdOnJuni,
  myTurnToDing,
];
