import assert from 'node:assert/strict';
import { test } from 'node:test';
import { cpSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { chromium, expect } from '@playwright/test';
import { startOffice } from '../lib/office.ts';
import { emitEvent } from '../lib/events.ts';
import { acquireLock } from '../lib/lock.ts';

test('real Pixel renderer shows events, reloads current state, and fits desktop/mobile', { timeout: 60_000 }, async () => {
  const source = resolve(import.meta.dirname, '../..');
  const temp = mkdtempSync(join(tmpdir(), 'pixel-office-e2e-'));
  let office; let browser; let release;
  try {
    for (const dir of ['office', 'office-dist']) cpSync(join(source, dir), join(temp, dir), { recursive: true });
    const state = join(temp, 'state'); mkdirSync(state);
    release = acquireLock(state);
    const base = { version: 1, timestamp: new Date().toISOString(), run_id: '20260919T120000Z-aabbcc',
      worker: 'codex-1', phase: 'test', event: 'started', activity: 'reviewing', duration_ms: null, available_at: null };
    emitEvent(state, base);
    emitEvent(state, { ...base, worker: 'claude-pro', phase: 'browser_qa', event: 'deferred', activity: 'waiting', available_at: '2026-09-19T16:00:00.000Z' });
    const discovered = [
      { key: 'codex:website', provider: 'codex', project: 'Website', title: 'Build the account settings page', status: 'active', detail: 'Working', updated_at: new Date().toISOString() },
      { key: 'claude:website', provider: 'claude', project: 'Website', title: 'Review accessibility improvements', status: 'completed', detail: 'Completed', updated_at: new Date().toISOString() },
      { key: 'codex:stale', provider: 'codex', project: 'Mobile app', title: 'Update onboarding flow', status: 'active', detail: 'Working', updated_at: new Date(Date.now() - 86_400_000).toISOString() },
    ];
    office = await startOffice(temp, 0, () => discovered);
    browser = await chromium.launch(process.env.CI ? {} : { channel: 'chrome' });
    const page = await browser.newPage({ viewport: { width: 1400, height: 1050 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.addInitScript(() => { window.__PIXEL_AGENTS_E2E = true; });
    await page.goto(office.url);
    await expect(page.locator('#connection')).toContainText('Live');
    await expect(page.locator('#workers')).toContainText('Waiting for quota');
    await expect(page.locator('#workers')).toContainText('Reviewing');
    await expect(page.locator('.scene')).toHaveCSS('height', /^(6[6-9][0-9]|[7-9][0-9]{2})px$/);
    await expect(page.locator('#kanban')).toContainText('Scrumboard');
    await expect(page.locator('#board-columns .kanban-column')).toHaveCount(6);
    await expect(page.locator('#board-summary')).toContainText('work items');
    const workerKey = await page.locator('#workers article[data-agent-key^="codex:"]').first().getAttribute('data-agent-key');
    const workerCard = page.locator(`.board-card[data-agent-key="${workerKey}"]`).first();
    await workerCard.hover();
    await expect(page.locator(`#workers article[data-agent-key="${workerKey}"].worker-highlight`)).toHaveCount(1);
    await expect(workerCard).toHaveClass(/worker-highlight/);
    await page.mouse.move(0, 0);
    const canvas = page.frameLocator('iframe').locator('canvas');
    await expect(canvas).toBeVisible();
    const frame = page.frames()[1];
    await expect.poll(() => frame.evaluate(() => window.__pixelAgentsTestHooks?.messageLog?.some(m => m.type === 'agentToolStart'))).toBe(true);
    await page.waitForTimeout(2_500);
    await expect.poll(() => frame.evaluate(() => window.__pixelAgentsTestHooks?.getCharacters?.().some(c => c.bubbleType === 'waiting'))).toBe(true);
    assert.equal(await page.frameLocator('iframe').locator('button:visible').count(), 0);
    await page.locator('#expand').click();
    await expect(page.locator('body')).toHaveClass(/office-focus/);
    await expect(page.getByRole('complementary', { name: 'Project management dashboard' })).toBeVisible();
    await expect(page.locator('#metrics [data-kind=active] strong')).toHaveText('2');
    await expect(page.locator('#attention')).toContainText('Confirm this agent is still running');
    const sceneBox = await page.locator('.office-stage').boundingBox();
    const dashboardBox = await page.locator('#dashboard').boundingBox();
    const boardBox = await page.locator('#kanban').boundingBox();
    assert.ok(sceneBox.x + sceneBox.width <= dashboardBox.x + 1, 'dashboard must sit beside the office');
    assert.ok(boardBox.y >= sceneBox.y + sceneBox.height - 2, 'Scrumboard must sit below the office in expanded view');
    await expect(page.locator('#office-size')).toHaveValue('68');
    await page.locator('#office-size').focus();
    await page.locator('#office-size').press('ArrowRight');
    await page.locator('#office-size').press('ArrowRight');
    await page.locator('#office-size').press('ArrowRight');
    await page.locator('#office-size').press('ArrowRight');
    await expect(page.locator('#office-size')).toHaveValue('72');
    await expect(page.locator('#office-board-splitter')).toHaveAttribute('aria-valuenow', '72');
    await page.locator('#board-collapse').click();
    await expect(page.locator('#board-columns')).toBeHidden();
    await page.locator('#board-collapse').click();
    await expect(page.locator('#board-columns')).toBeVisible();
    await page.locator('#projects button').filter({ hasText: 'Website' }).click();
    await expect(page.locator('#task-list details')).toHaveCount(2);
    await page.locator('#task-search').fill('accessibility');
    await expect(page.locator('#task-list details')).toHaveCount(1);
    await page.locator('#task-list summary').click();
    await page.waitForTimeout(1700);
    await expect(page.locator('#task-list details')).toHaveAttribute('open', '');
    await expect(page.locator('#task-search')).toHaveValue('accessibility');
    await page.locator('#task-search').fill('');
    await page.locator('#project-filter').selectOption('');
    await page.locator('.dashboard-scroll').evaluate(el => { el.scrollTop = 0; });
    mkdirSync(join(source, 'test-results'), { recursive: true });
    await page.screenshot({ path: join(source, 'test-results/office-dashboard.png') });
    await page.keyboard.press('Escape');
    await expect(page.locator('body')).not.toHaveClass(/office-focus/);
    await expect(page.locator('#dashboard')).toBeHidden();
    emitEvent(state, { ...base, event: 'completed', activity: 'waiting', duration_ms: 1000 });
    await expect(page.locator('#workers')).toContainText('Completed');
    await page.reload();
    await expect(page.locator('#workers')).toContainText('Completed');
    await expect(canvas).toBeVisible();
    await expect.poll(() => page.frames()[1].evaluate(() => window.__pixelAgentsTestHooks?.messageLog?.some(m => m.type === 'existingAgents'))).toBe(true);
    mkdirSync(join(source, 'test-results'), { recursive: true });
    await page.screenshot({ path: join(source, 'test-results/office-e2e.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(canvas).toBeVisible();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: join(source, 'test-results/office-mobile.png'), fullPage: true });
    await page.locator('#expand').click();
    await expect(page.locator('#dashboard')).toBeVisible();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const mobileScene = await page.locator('.office-stage').boundingBox();
    const mobileDashboard = await page.locator('#dashboard').boundingBox();
    assert.ok(mobileScene.y + mobileScene.height <= mobileDashboard.y + 1, 'mobile dashboard stacks below the visible office');
    await page.screenshot({ path: join(source, 'test-results/office-dashboard-mobile.png') });
    await page.route('**/api/status', route => route.abort());
    await expect(page.locator('#dashboard-live')).toContainText('Feed unavailable');
    await expect(page.locator('#projects')).toContainText('Website');
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close(); await office?.close(); release?.(); rmSync(temp, { recursive: true, force: true });
  }
});
