#!/usr/bin/env node
/**
 * Translate story content for all non-English locale files.
 * Replaces English placeholder text with proper translations.
 *
 * Data format: S['storyKey'] = { locale: [title, page1, page2, page3, page4, page5] }
 * The script finds each story block in the locale file and replaces the 6 field values.
 *
 * Usage: node scripts/translate-stories.js
 */
const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, '..', 'locales');
const LOCALES = ['ar','da','de','es','fr','it','ja','la','nl','pl','pt','tr','zh'];
const FIELDS = ['title', 'page1', 'page2', 'page3', 'page4', 'page5'];
const LANG = {ar:'Arabic',da:'Danish',de:'German',es:'Spanish',fr:'French',it:'Italian',ja:'Japanese',la:'Latin',nl:'Dutch',pl:'Polish',pt:'Portuguese',tr:'Turkish',zh:'Chinese'};

// ── Story translation data ──────────────────────────────────────────
// Format: S['storyKey'] = { locale: [title, page1, page2, page3, page4, page5] }
const S = {};

// ═══ SPELLING STORIES ═══

// Story 1: owlCantSleep (abc-animals)
S['owlCantSleep'] = {
  ar: ['البومة لا تستطيع النوم','طارت البومة إلى الحظيرة المريحة. كان أحدهم يخرخر بهدوء على كومة قش دافئة. من هو؟ هل تستطيع تهجئة اسمه؟','أطلّت البومة في بيت الكلب. كان ___ ينخر ويحلم بالعصي، ملتفاً في ___ المريح.','بجانب السياج، سمعت البومة صوت قرقرة لطيف. صديق ناعم كان يستقر على عش من البيض.','في الحظيرة، كان ___ ملتفاً في ___ نائماً بشخير خفيف.','كل أصدقائه نائمون بسلام. البومة تتثاءب أكبر تثاؤبة. الآن تهجّ اسم البومة!'],
  da: ['Uglen kan ikke sove','Uglen fløj til den hyggelige lade. Nogen spandt blødt på en varm høballe. Hvem er det? Kan du stave deres navn?','Uglen kiggede ind i hundehuset. En ___ snorkede og drømte om pinde, krøllet sammen i sit hyggelige ___.','Ved hegnet hørte Uglen en blid klukken. En dunblød ven slog sig ned på en rede af æg.','I folden lå en ___ rullet sammen i ___, dybt i søvn med et lille snork.','Alle hans venner sover trygt. Uglen gaber sit største gab. Stav nu Uglens eget navn!'],
  de: ['Eule kann nicht schlafen','Eule flog zur gemütlichen Scheune. Jemand schnurrte leise auf einem warmen Heuballen. Wer ist es? Kannst du den Namen buchstabieren?','Eule schaute in die Hundehütte. Ein ___ schnarchte und träumte von Stöcken, eingerollt in seinem gemütlichen ___.','Am Zaun hörte Eule ein sanftes Gackern. Ein flauschiger Freund ließ sich auf einem Nest voller Eier nieder.','Im Gehege lag ein ___ eingerollt im ___, tief schlafend mit einem kleinen Schnarcher.','Alle seine Freunde schlafen fest. Eule gähnt sein größtes Gähnen. Buchstabiere jetzt Eules eigenen Namen!'],
  es: ['El Búho no puede dormir','El Búho voló al granero acogedor. Alguien ronroneaba suavemente sobre una cálida paca de heno. ¿Quién es? ¿Puedes deletrear su nombre?','El Búho se asomó a la caseta. Un ___ roncaba y soñaba con palos, acurrucado en su acogedor ___.','Junto a la valla, el Búho escuchó un suave cacareo. Un amigo esponjoso se acomodaba en un nido de huevos.','En el corral, un ___ estaba acurrucado en el ___, dormido con un pequeño ronquido.','Todos sus amigos duermen profundamente. El Búho bosteza su bostezo más grande. ¡Ahora deletrea el nombre del Búho!'],
  fr: ['Hibou ne peut pas dormir','Hibou a volé vers la grange douillette. Quelqu\\\'un ronronnait doucement sur une botte de foin chaude. Qui est-ce ? Peux-tu épeler son nom ?','Hibou a jeté un coup d\\\'œil dans la niche. Un ___ ronflait et rêvait de bâtons, blotti dans son ___ douillet.','Près de la clôture, Hibou a entendu un doux caquètement. Un ami duveteux s\\\'installait sur un nid d\\\'œufs.','Dans l\\\'enclos, un ___ était blotti dans le ___, endormi avec un petit ronflement.','Tous ses amis dorment profondément. Hibou fait son plus grand bâillement. Maintenant épelle le nom de Hibou !'],
  it: ['Il Gufo non riesce a dormire','Il Gufo volò al fienile accogliente. Qualcuno faceva le fusa dolcemente su una calda balla di fieno. Chi è? Sai sillabare il suo nome?','Il Gufo sbirciò nel canile. Un ___ russava e sognava bastoncini, raggomitolato nel suo accogliente ___.','Vicino alla staccionata, il Gufo sentì un dolce chiocciare. Un amico morbido si sistemava su un nido di uova.','Nel recinto, un ___ era raggomitolato nel ___, addormentato con un piccolo russare.','Tutti i suoi amici dormono profondamente. Il Gufo sbadiglia il suo sbadiglio più grande. Ora sillabia il nome del Gufo!'],
  ja: ['フクロウがねむれない','フクロウはここちよいなやにとんでいきました。だれかがあたたかいほしくさのうえでそっとゴロゴロいっています。だれかな？なまえをつづれるかな？','フクロウはいぬごやをのぞきました。___がぼうをゆめみながらいびきをかいて、ここちよい___でまるくなっています。','さくのそばで、フクロウはやさしいコッコッというおとをききました。ふわふわのともだちがたまごのすにおちついています。','おりのなかで、___が___のなかでまるくなって、ちいさないびきですやすやねています。','ともだちはみんなぐっすりねています。フクロウはいちばんおおきなあくびをします。さあ、フクロウのなまえをつづろう！'],
  la: ['Bubo dormire non potest','Bubo ad horreum commodum volavit. Aliquis in calido faeni volumine leniter murmurabat. Quis est? Potesne nomen litteris ponere?','Bubo in canis casam prospexit. ___ stertebat et de baculis somniabat, in commodo ___ convolutus.','Iuxta saepem, Bubo lenem glocitationem audivit. Amicus mollis in nido ovorum considebat.','In saepto, ___ in ___ convolutus dormiebat cum parvo stertore.','Omnes amici eius profunde dormiunt. Bubo maximum oscitat. Nunc Bubonis nomen littera!'],
  nl: ['Uil kan niet slapen','Uil vloog naar de gezellige schuur. Iemand spinde zachtjes op een warme hooibaal. Wie is het? Kun je de naam spellen?','Uil gluurde in het hondenhok. Een ___ snurkte en droomde van stokjes, opgerold in zijn gezellige ___.','Bij het hek hoorde Uil een zacht gekakel. Een donzig vriendje nestelde zich op een nest met eieren.','In het hok lag een ___ opgerold in het ___, diep in slaap met een klein snurkje.','Al zijn vriendjes slapen diep. Uil gaapt zijn grootste gaap. Spel nu Uils eigen naam!'],
  pl: ['Sowa nie może zasnąć','Sowa poleciała do przytulnej stodoły. Ktoś mruczał cicho na ciepłej beli siana. Kto to? Czy potrafisz przeliterować imię?','Sowa zajrzała do budy. ___ chrapał i śnił o palikach, zwinięty w swoim przytulnym ___.','Przy płocie Sowa usłyszała łagodne gdakanie. Puszysty przyjaciel układał się na gnieździe z jajkami.','W zagrodzie ___ zwinął się w ___, śpiąc z cichym pochrapywaniem.','Wszyscy przyjaciele śpią spokojnie. Sowa ziewa najszerzej. Teraz przeliteruj imię Sowy!'],
  pt: ['A Coruja não consegue dormir','A Coruja voou para o celeiro aconchegante. Alguém ronronava suavemente em um fardo de feno quentinho. Quem é? Você sabe soletrar o nome?','A Coruja espiou na casinha do cachorro. Um ___ roncava e sonhava com gravetos, enrolado em seu aconchegante ___.','Perto da cerca, a Coruja ouviu um suave cacarejar. Um amigo fofinho se acomodava em um ninho de ovos.','No cercado, um ___ estava enrolado no ___, dormindo com um ronquinho.','Todos os amigos dormem profundamente. A Coruja boceja seu maior bocejo. Agora soletre o nome da Coruja!'],
  tr: ['Baykuş uyuyamıyor','Baykuş rahat ahıra uçtu. Birisi sıcak bir saman balyasında usulca mırıldanıyordu. Kim o? İsmini heceleyebilir misin?','Baykuş kulübeye baktı. Bir ___ horluyordu ve çubuklarla hayal kuruyordu, rahat ___\'ında kıvrılmıştı.','Çitin yanında Baykuş yumuşak bir gıdaklama duydu. Tüylü bir arkadaş yumurta yuvasına yerleşiyordu.','Ağılda bir ___ ___\'ın içinde kıvrılmış, küçük bir horlamayla uyuyordu.','Tüm arkadaşları deliksiz uyuyor. Baykuş en büyük esnemesini esnedi. Şimdi Baykuş\\\'un ismini hecele!'],
  zh: ['猫头鹰睡不着','猫头鹰飞到了温馨的谷仓。有人在温暖的干草堆上轻轻地打呼噜。是谁呢？你能拼写他们的名字吗？','猫头鹰偷看了狗窝。一只___在打呼噜，梦见棍子，蜷缩在舒适的___里。','在围栏旁，猫头鹰听到了轻柔的咯咯声。一个毛茸茸的朋友正在鸡蛋窝里安顿下来。','在围栏里，一只___蜷缩在___里，轻轻打着呼噜睡着了。','所有的朋友都睡得很香。猫头鹰打了最大的哈欠。现在拼写猫头鹰的名字吧！'],
};

// Story 2: teddysDayOut (first-words)
S['teddysDayOut'] = {
  ar: ['يوم الدبدوب الكبير','هرب الدبدوب من صندوق الألعاب! بجانب الباب الأمامي، ترك شيئاً يحب ارتداءه على رأسه.','في المطبخ، أقام الدبدوب حفلة شاي. هناك ___ صغير وبعض ___ على الطاولة.','نظر الدبدوب من النافذة. في الخارج، الشيء الكبير الدافئ في السماء جعل كل شيء يتوهج!','يا إلهي، شعر الدبدوب بالنعاس! صعد على أنعم ___ لأخذ ___ صغيرة.','حان وقت العودة! لوّح الدبدوب وقفز على الشيء الأحمر الكبير الذي يصدر صوت بيب بيب!'],
  da: ['Bamses store dag ud','Bamse er undsluppet fra legetøjskassen! Ved hoveddøren efterlod han noget han kan lide at have på hovedet.','I køkkenet holdt Bamse teselskab. Der er en lille ___ og noget ___ tilbage på bordet.','Bamse kiggede ud af vinduet. Udenfor fik den store varme ting på himlen alt til at gløde!','Åh nej, Bamse blev søvnig! Han klatrede op på den blødeste ___ for en lille ___.','Tid til at tage hjem! Bamse vinkede farvel og hoppede op på den store røde ting der siger bip bip!'],
  de: ['Teddys großer Ausflug','Teddy ist aus der Spielkiste entkommen! An der Haustür hat er etwas hinterlassen, das er gerne auf dem Kopf trägt.','In der Küche hat Teddy eine Teeparty gefeiert. Da ist eine kleine ___ und etwas ___ auf dem Tisch.','Teddy schaute durch das Fenster. Draußen ließ das große warme Ding am Himmel alles leuchten!','Oh je, Teddy wurde müde! Er kletterte auf das weichste ___ für ein kleines ___.','Zeit nach Hause zu gehen! Teddy winkte zum Abschied und sprang auf das große rote Ding das piep piep macht!'],
  es: ['El gran día de Osito','¡Osito se ha escapado de la caja de juguetes! Junto a la puerta, dejó algo que le gusta llevar en la cabeza.','En la cocina, Osito hizo una fiesta de té. Hay una pequeña ___ y algo de ___ en la mesa.','Osito miró por la ventana. ¡Afuera, la cosa grande y cálida en el cielo hacía que todo brillara!','¡Ay, Osito se puso somnoliento! Se subió al ___ más suave para una pequeña ___.','¡Hora de volver a casa! Osito se despidió y saltó a la cosa roja grande que hace bip bip!'],
  fr: ['La grande sortie de Nounours','Nounours s\\\'est échappé de la boîte à jouets ! Près de la porte, il a laissé quelque chose qu\\\'il aime porter sur la tête.','Dans la cuisine, Nounours a fait un goûter. Il reste un petit ___ et du ___ sur la table.','Nounours a regardé par la fenêtre. Dehors, la grande chose chaude dans le ciel faisait tout briller !','Oh là là, Nounours a sommeil ! Il est monté sur le ___ le plus doux pour une petite ___.','C\\\'est l\\\'heure de rentrer ! Nounours a fait au revoir et a sauté sur la grande chose rouge qui fait bip bip !'],
  it: ['La grande giornata di Orsetto','Orsetto è scappato dalla scatola dei giocattoli! Vicino alla porta, ha lasciato qualcosa che gli piace indossare in testa.','In cucina, Orsetto ha fatto una festa del tè. C\\\'è un piccolo ___ e un po\\\'di ___ sul tavolo.','Orsetto ha sbirciato dalla finestra. Fuori, la grande cosa calda nel cielo faceva brillare tutto!','Oh no, Orsetto ha sonno! Si è arrampicato sul ___ più morbido per un piccolo ___.','È ora di tornare a casa! Orsetto ha salutato ed è saltato sulla grande cosa rossa che fa bip bip!'],
  ja: ['テディのだいぼうけん','テディベアがおもちゃばこからにげだした！げんかんのそばに、あたまにかぶるのがすきなものをおいていきました。','だいどころで、テディはおちゃかいをしました。テーブルにちいさな___とすこしの___がのこっています。','テディはまどからのぞきました。そとでは、そらのおおきくてあたたかいものがすべてをかがやかせていました！','たいへん、テディはねむくなった！いちばんやわらかい___にのぼって、ちょっと___しました。','おうちにかえるじかんだ！テディはてをふって、ビービーいうおおきなあかいものにとびのりました！'],
  la: ['Magnus dies Ursi','Ursus e cista ludicrorum evasit! Iuxta ianuam, aliquid quod in capite gerere amat reliquit.','In culina, Ursus convivium theae habuit. Parva ___ et aliquid ___ in mensa relicta sunt.','Ursus per fenestram prospexit. Foris, magna calida res in caelo omnia lucere fecit!','Eheu, Ursus somnolentus factus est! In mollissimum ___ ascendit ad parvum ___.','Tempus domum redire! Ursus valedicit et in magnam rem rubram quae bip bip facit insilit!'],
  nl: ['Teddys grote dag uit','Teddybeer is ontsnapt uit de speelgoeddoos! Bij de voordeur liet hij iets achter dat hij graag op zijn hoofd draagt.','In de keuken hield Teddy een theepartijtje. Er staat een klein ___ en wat ___ op tafel.','Teddy gluurde door het raam. Buiten liet het grote warme ding aan de hemel alles gloeien!','O jee, Teddy werd slaperig! Hij klom op het zachtste ___ voor een klein ___.','Tijd om naar huis te gaan! Teddy zwaaide gedag en sprong op het grote rode ding dat piep piep doet!'],
  pl: ['Wielki dzień Misia','Miś uciekł z pudełka z zabawkami! Przy drzwiach zostawił coś, co lubi nosić na głowie.','W kuchni Miś urządził herbatkę. Na stole jest mały ___ i trochę ___.','Miś zajrzał przez okno. Na zewnątrz wielka ciepła rzecz na niebie sprawiała, że wszystko lśniło!','Ojej, Miś się zaspał! Wdrapał się na najmiększy ___ na małą ___.','Czas wracać do domu! Miś pomachał i wskoczył na wielką czerwoną rzecz, która robi bip bip!'],
  pt: ['O grande dia do Ursinho','O Ursinho escapou da caixa de brinquedos! Perto da porta, deixou algo que gosta de usar na cabeça.','Na cozinha, o Ursinho fez uma festa do chá. Tem um pequeno ___ e um pouco de ___ na mesa.','O Ursinho espiou pela janela. Lá fora, a coisa grande e quente no céu fazia tudo brilhar!','Oh não, o Ursinho ficou sonolento! Subiu no ___ mais macio para uma pequena ___.','Hora de voltar para casa! O Ursinho acenou e pulou na coisa vermelha grande que faz bip bip!'],
  tr: ['Ayıcığın Büyük Günü','Ayıcık oyuncak kutusundan kaçtı! Kapının yanında kafasına takmayı sevdiği bir şey bıraktı.','Mutfakta Ayıcık çay partisi yaptı. Masada küçük bir ___ ve biraz ___ kaldı.','Ayıcık pencereden baktı. Dışarıda gökyüzündeki büyük sıcak şey her şeyi parlattı!','Eyvah, Ayıcık uykusu geldi! En yumuşak ___\\\'a tırmanıp küçük bir ___ yaptı.','Eve dönme zamanı! Ayıcık el salladı ve bip bip yapan büyük kırmızı şeye atladı!'],
  zh: ['泰迪的大冒险','泰迪熊从玩具箱里逃出来了！在前门旁，他留下了喜欢戴在头上的东西。','在厨房里，泰迪开了个茶话会。桌上还有一个小___和一些___。','泰迪从窗户往外看。外面，天空中那个又大又温暖的东西让一切都发光！','哎呀，泰迪困了！他爬上最柔软的___，小睡了一___。','该回家了！泰迪挥手告别，跳上了那个会发出嘀嘀声的大红色东西！'],
};

// Story 3: painterMouse (colour-spelling)
S['painterMouse'] = {
  ar: ['الفأر الرسام','اكتشف فأر صغير فراشي سحرية! فقدت الورود لونها. ما اللون الذي يجب أن تكون عليه؟','أمسك الفأر بالفرشاة التالية. يجب أن يكون ___ بلون ___ مرة أخرى!','أزهار الكرز تحتاج لونها الجميل! لوّح الفأر بالفرشاة وانتظر الكلمة السحرية.','صندوق الكنز يحتاج بريق ___، مثل ___ المتلألئ فوق!','الفرشاة الأخيرة! الجدار الحجري القديم يحتاج لونه. رسم الفأر آخر لمسة — العالم جميل مرة أخرى!'],
  da: ['Malermusen','En lille mus opdager magiske pensler! Roserne har mistet deres farve. Hvilken farve skal de være?','Musen tager den næste pensel. ___ skal være ___ igen!','Kirsebærblomstrene har brug for deres smukke farve tilbage! Musen vifter med penslen og venter på det magiske ord.','Skattekisten har brug for en ___ glans, som den ___ der skinner ovenover!','Den sidste pensel! Den gamle stenmur har brug for sin farve. Musen maler det sidste strøg — verden er smuk igen!'],
  de: ['Die Malermaus','Eine kleine Maus entdeckt magische Pinsel! Die Rosen haben ihre Farbe verloren. Welche Farbe sollten sie haben?','Maus nimmt den nächsten Pinsel. Der ___ soll wieder ___ sein!','Die Kirschblüten brauchen ihre schöne Farbe zurück! Maus wedelt mit dem Pinsel und wartet auf das Zauberwort.','Die Schatztruhe braucht einen ___ Schimmer, wie der ___ der oben scheint!','Der letzte Pinsel! Die alte Steinmauer braucht ihre Farbe. Maus malt den letzten Strich — die Welt ist wieder schön!'],
  es: ['El Ratón Pintor','¡Un ratoncito descubre pinceles mágicos! Las rosas han perdido su color. ¿Qué color deberían tener?','El ratón toma el siguiente pincel. ¡El ___ debería ser ___ de nuevo!','¡Los cerezos necesitan su hermoso color! El ratón agita el pincel y espera la palabra mágica.','¡El cofre del tesoro necesita un brillo ___, como el ___ que brilla arriba!','¡El último pincel! El viejo muro de piedra necesita su color. El ratón pinta la última pincelada — ¡el mundo es hermoso otra vez!'],
  fr: ['La Souris Peintre','Une petite souris découvre des pinceaux magiques ! Les roses ont perdu leur couleur. Quelle couleur devraient-elles être ?','La souris prend le pinceau suivant. Le ___ devrait être ___ à nouveau !','Les cerisiers en fleurs ont besoin de leur belle couleur ! La souris agite le pinceau et attend le mot magique.','Le coffre au trésor a besoin d\\\'un éclat ___, comme le ___ qui brille au-dessus !','Le dernier pinceau ! Le vieux mur de pierre a besoin de sa couleur. La souris peint le dernier trait — le monde est beau à nouveau !'],
  it: ['Il Topo Pittore','Un topolino scopre pennelli magici! Le rose hanno perso il loro colore. Di che colore dovrebbero essere?','Il topo prende il pennello successivo. Il ___ dovrebbe essere di nuovo ___!','I fiori di ciliegio hanno bisogno del loro bel colore! Il topo agita il pennello e aspetta la parola magica.','Il forziere ha bisogno di un bagliore ___, come il ___ che brilla sopra!','L\\\'ultimo pennello! Il vecchio muro di pietra ha bisogno del suo colore. Il topo dipinge l\\\'ultimo tratto — il mondo è di nuovo bello!'],
  ja: ['えかきネズミ','ちいさなネズミがまほうのふでをみつけた！バラがいろをうしなってしまいました。なにいろにすればいい？','ネズミはつぎのふでをとりました。___はまた___になるべきだ！','さくらのはなにきれいないろがもどらないと！ネズミがふでをふって、まほうのことばをまちます。','たからばこには___のかがやきがひつよう、うえでひかる___みたいに！','さいごのふで！ふるいいしかべにいろがひつよう。ネズミがさいごのひとぬり — せかいはまたきれいになった！'],
  la: ['Mus Pictor','Parvus mus penicillos magicos invenit! Rosae colorem amiserunt. Quis color esse debent?','Mus proximum penicillum sumit. ___ iterum ___ esse debet!','Flores cerasi pulchrum colorem recuperare debent! Mus penicillum agitat et verbum magicum exspectat.','Arca thesauri splendorem ___ eget, sicut ___ supra fulgens!','Ultimus penicillus! Vetus murus lapideus colorem suum eget. Mus ultimum ictum pingit — mundus iterum pulcher est!'],
  nl: ['De Schildermuis','Een klein muisje ontdekt magische penselen! De rozen hebben hun kleur verloren. Welke kleur moeten ze zijn?','Muis pakt het volgende penseel. De ___ moet weer ___ worden!','De kersenbloesems hebben hun mooie kleur nodig! Muis zwaait met het penseel en wacht op het toverwoord.','De schatkist heeft een ___ glans nodig, zoals de ___ die erboven schijnt!','Het laatste penseel! De oude stenen muur heeft zijn kleur nodig. Muis schildert de laatste streek — de wereld is weer mooi!'],
  pl: ['Mysz Malarz','Mała myszka odkrywa magiczne pędzle! Róże straciły kolor. Jaki kolor powinny mieć?','Myszka bierze następny pędzel. ___ powinien znów być ___!','Kwiaty wiśni potrzebują swojego pięknego koloru! Myszka macha pędzlem i czeka na magiczne słowo.','Skrzynia ze skarbem potrzebuje ___ blasku, jak ___ świecący w górze!','Ostatni pędzel! Stary kamienny mur potrzebuje koloru. Myszka maluje ostatnie pociągnięcie — świat jest znów piękny!'],
  pt: ['O Rato Pintor','Um ratinho descobre pincéis mágicos! As rosas perderam sua cor. Que cor deveriam ter?','O rato pega o próximo pincel. O ___ deveria ser ___ novamente!','As flores de cerejeira precisam de sua bela cor! O rato agita o pincel e espera a palavra mágica.','O baú do tesouro precisa de um brilho ___, como o ___ brilhando lá em cima!','O último pincel! O velho muro de pedra precisa de sua cor. O rato pinta a última pincelada — o mundo está bonito novamente!'],
  tr: ['Ressam Fare','Küçük bir fare sihirli fırçalar keşfeder! Güller renklerini kaybetmiş. Ne renk olmalılar?','Fare sonraki fırçayı alır. ___ tekrar ___ olmalı!','Kiraz çiçekleri güzel renklerini geri istiyor! Fare fırçayı sallar ve sihirli kelimeyi bekler.','Hazine sandığı bir ___ parıltısına ihtiyaç duyuyor, yukarıda parlayan ___ gibi!','Son fırça! Eski taş duvarın rengine ihtiyacı var. Fare son darbeyi vurur — dünya yine güzel!'],
  zh: ['画家小老鼠','一只小老鼠发现了魔法画笔！玫瑰失去了颜色。它们应该是什么颜色？','小老鼠拿起下一支画笔。___应该重新变成___！','樱花需要恢复美丽的颜色！小老鼠挥动画笔，等待魔法词语。','宝箱需要___的光芒，就像上面闪耀的___一样！','最后一支画笔！古老的石墙需要它的颜色。小老鼠画下最后一笔——世界又变得美丽了！'],
};

// Story 4: shapesInClouds (shape-spelling)
S['shapesInClouds'] = {
  ar: ['أشكال في الغيوم','استلقى الأرنب على العشب ونظر للأعلى. الغيوم تشكل أشكالاً! هل تراها أيضاً؟','هذه الغيمة تبدو مثل ___! دائرية ___. هل يمكنك تهجئة الشكل؟','الريح تهب وتتغير الغيوم. الآن هناك شيء بأربع زوايا!','بالقرب من الشمس، ___ بثلاثة أضلاع يتلألأ مثل ___.','أبتسم الأرنب. الغيوم تصنع أجمل الأشكال! أي شكل تراه أنت؟'],
  da: ['Former i skyerne','Kanin lagde sig i græsset og kiggede op. Skyerne danner former! Kan du også se dem?','Den sky ligner en ___! Rund og ___. Kan du stave formen?','Vinden blæser og skyerne ændrer sig. Nu er der noget med fire hjørner!','Nær solen glitrer en ___ med tre sider som en ___.','Kanin smilede. Skyerne laver de smukkeste former! Hvilken form kan du se?'],
  de: ['Formen in den Wolken','Hase legte sich ins Gras und schaute nach oben. Die Wolken bilden Formen! Siehst du sie auch?','Diese Wolke sieht aus wie ein ___! Rund und ___. Kannst du die Form buchstabieren?','Der Wind bläst und die Wolken verändern sich. Jetzt gibt es etwas mit vier Ecken!','Nahe der Sonne glitzert ein ___ mit drei Seiten wie ein ___.','Hase lächelte. Die Wolken machen die schönsten Formen! Welche Form siehst du?'],
  es: ['Formas en las nubes','Conejo se acostó en la hierba y miró hacia arriba. ¡Las nubes forman figuras! ¿Tú también las ves?','¡Esa nube parece un ___! Redonda y ___. ¿Puedes deletrear la forma?','El viento sopla y las nubes cambian. ¡Ahora hay algo con cuatro esquinas!','Cerca del sol, un ___ con tres lados brilla como un ___.','Conejo sonrió. ¡Las nubes hacen las formas más bonitas! ¿Qué forma ves tú?'],
  fr: ['Formes dans les nuages','Lapin s\\\'est allongé dans l\\\'herbe et a regardé en haut. Les nuages forment des formes ! Les vois-tu aussi ?','Ce nuage ressemble à un ___ ! Rond et ___. Peux-tu épeler la forme ?','Le vent souffle et les nuages changent. Maintenant il y a quelque chose avec quatre coins !','Près du soleil, un ___ à trois côtés scintille comme un ___.','Lapin a souri. Les nuages font les plus belles formes ! Quelle forme vois-tu ?'],
  it: ['Forme nelle nuvole','Coniglio si è sdraiato sull\\\'erba e ha guardato in alto. Le nuvole formano delle forme! Le vedi anche tu?','Quella nuvola sembra un ___! Rotonda e ___. Sai sillabare la forma?','Il vento soffia e le nuvole cambiano. Ora c\\\'è qualcosa con quattro angoli!','Vicino al sole, un ___ con tre lati brilla come un ___.','Coniglio ha sorriso. Le nuvole fanno le forme più belle! Quale forma vedi tu?'],
  ja: ['くものなかのかたち','うさぎがくさのうえにねころんで、うえをみました。くもがかたちをつくっている！きみにもみえる？','このくもは___みたい！まるくて___。かたちをつづれるかな？','かぜがふいて、くもがかわります。いまよつのかどがあるものがみえるよ！','たいようのそばで、みっつのへんがある___が___のようにきらきらしています。','うさぎはにっこりしました。くもはいちばんきれいなかたちをつくるね！きみにはなにがみえる？'],
  la: ['Formae in nubibus','Lepus in herba iacuit et sursum spectavit. Nubes formas faciunt! Videsne eas quoque?','Illa nubes ___ similis est! Rotunda et ___. Potesne formam litteris ponere?','Ventus flat et nubes mutantur. Nunc aliquid cum quattuor angulis est!','Prope solem, ___ tribus lateribus sicut ___ scintillat.','Lepus subrisit. Nubes pulcherrimas formas faciunt! Quam formam vides?'],
  nl: ['Vormen in de wolken','Konijn ging in het gras liggen en keek omhoog. De wolken maken vormen! Zie jij ze ook?','Die wolk lijkt op een ___! Rond en ___. Kun je de vorm spellen?','De wind blaast en de wolken veranderen. Nu is er iets met vier hoeken!','Dicht bij de zon glinstert een ___ met drie zijden als een ___.','Konijn glimlachte. De wolken maken de mooiste vormen! Welke vorm zie jij?'],
  pl: ['Kształty w chmurach','Królik położył się na trawie i spojrzał w górę. Chmury tworzą kształty! Czy ty też je widzisz?','Ta chmura wygląda jak ___! Okrągła i ___. Czy potrafisz przeliterować kształt?','Wiatr wieje i chmury się zmieniają. Teraz jest coś z czterema rogami!','Blisko słońca ___ o trzech bokach lśni jak ___.','Królik się uśmiechnął. Chmury tworzą najpiękniejsze kształty! Jaki kształt widzisz ty?'],
  pt: ['Formas nas nuvens','Coelho deitou na grama e olhou para cima. As nuvens formam figuras! Você também as vê?','Aquela nuvem parece um ___! Redonda e ___. Você sabe soletrar a forma?','O vento sopra e as nuvens mudam. Agora tem algo com quatro cantos!','Perto do sol, um ___ com três lados brilha como um ___.','Coelho sorriu. As nuvens fazem as formas mais bonitas! Que forma você vê?'],
  tr: ['Bulutlardaki Şekiller','Tavşan çimenlere uzandı ve yukarı baktı. Bulutlar şekiller oluşturuyor! Sen de görüyor musun?','O bulut bir ___ gibi görünüyor! Yuvarlak ve ___. Şekli heceleyebilir misin?','Rüzgâr esiyor ve bulutlar değişiyor. Şimdi dört köşeli bir şey var!','Güneşin yanında, üç kenarlı bir ___ bir ___ gibi parlıyor.','Tavşan gülümsedi. Bulutlar en güzel şekilleri yapıyor! Sen hangi şekli görüyorsun?'],
  zh: ['云中的形状','兔子躺在草地上抬头看。云朵在变成各种形状！你也看到了吗？','那朵云看起来像一个___！圆圆的___。你能拼写这个形状吗？','风吹来，云朵变了。现在有个四个角的东西！','太阳旁边，一个有三条边的___像___一样闪闪发光。','兔子笑了。云朵做出最美的形状！你看到了什么形状？'],
};

// Story 5: firstDayFriends (first-words)
S['firstDayFriends'] = {
  ar: ['أصدقاء اليوم الأول','اليوم هو أول يوم في المدرسة! وصل طفل صغير حاملاً ___ مليء بالمفاجآت.','في الفصل، هناك ___ ملونة على كل طاولة. هل يمكنك تهجئة ما تراه؟','وقت اللعب! في الخارج هناك ___ كبير يلمع تحت ___. يا له من يوم رائع!','صديق جديد يشارك ___. يا لها من لفتة لطيفة! هل يمكنك تهجئة ما شاركه؟','نهاية يوم سعيد! الجميع يلوح بـ___. أول يوم كان مليئاً بالأصدقاء الجدد!'],
  da: ['Første dags venner','I dag er det første skoledag! Et lille barn ankom med en ___ fuld af overraskelser.','I klasseværelset er der farverige ___ på hvert bord. Kan du stave hvad du ser?','Leg! Udenfor er der en stor ___ der skinner under ___. Sikke en dag!','En ny ven deler sin ___. Hvor sødt! Kan du stave hvad der blev delt?','Slutningen på en glad dag! Alle vinker med ___. Første dag var fuld af nye venner!'],
  de: ['Freunde am ersten Tag','Heute ist der erste Schultag! Ein kleines Kind kam mit einer ___ voller Überraschungen.','Im Klassenzimmer sind bunte ___ auf jedem Tisch. Kannst du buchstabieren was du siehst?','Spielzeit! Draußen gibt es einen großen ___ der unter ___ glänzt. Was für ein Tag!','Ein neuer Freund teilt sein ___. Wie nett! Kannst du buchstabieren was geteilt wurde?','Ende eines glücklichen Tages! Alle winken mit ___. Der erste Tag war voller neuer Freunde!'],
  es: ['Amigos del primer día','¡Hoy es el primer día de escuela! Un niño pequeño llegó con una ___ llena de sorpresas.','En el aula hay ___ coloridos en cada mesa. ¿Puedes deletrear lo que ves?','¡Hora de jugar! Afuera hay un gran ___ brillando bajo el ___. ¡Qué día!','Un nuevo amigo comparte su ___. ¡Qué amable! ¿Puedes deletrear lo que compartió?','¡Fin de un día feliz! Todos saludan con ___. ¡El primer día estuvo lleno de nuevos amigos!'],
  fr: ['Amis du premier jour','Aujourd\\\'hui c\\\'est le premier jour d\\\'école ! Un petit enfant est arrivé avec un ___ plein de surprises.','Dans la classe, il y a des ___ colorés sur chaque table. Peux-tu épeler ce que tu vois ?','Récréation ! Dehors il y a un grand ___ qui brille sous le ___. Quelle journée !','Un nouvel ami partage son ___. Comme c\\\'est gentil ! Peux-tu épeler ce qu\\\'il a partagé ?','Fin d\\\'une journée heureuse ! Tout le monde fait au revoir avec ___. Le premier jour était plein de nouveaux amis !'],
  it: ['Amici del primo giorno','Oggi è il primo giorno di scuola! Un bambino è arrivato con uno ___ pieno di sorprese.','In classe ci sono ___ colorati su ogni tavolo. Sai sillabare quello che vedi?','Ricreazione! Fuori c\\\'è un grande ___ che brilla sotto il ___. Che giornata!','Un nuovo amico condivide il suo ___. Che gentile! Sai sillabare cosa ha condiviso?','Fine di una giornata felice! Tutti salutano con ___. Il primo giorno era pieno di nuovi amici!'],
  ja: ['はじめてのともだち','きょうはがっこうのはじめてのひ！ちいさなこどもが___いっぱいのサプライズをもってやってきました。','きょうしつでは、テーブルごとにカラフルな___があります。なにがみえるかつづれるかな？','あそびのじかん！そとにはおおきな___が___のしたでひかっています。すてきないちにち！','あたらしいともだちが___をわけてくれました。やさしいね！なにをわけたかつづれるかな？','たのしいいちにちのおわり！みんなが___でてをふっています。はじめてのひはあたらしいともだちでいっぱいでした！'],
  la: ['Amici primi diei','Hodie est primus dies scholae! Parvus puer cum ___ plena mirabilium advenit.','In schola, ___ colorata in omni mensa sunt. Potesne quod vides litteris ponere?','Tempus ludendi! Foris magnus ___ sub ___ fulget. Qualis dies!','Novus amicus ___ suum communicat. Quam benignum! Potesne quod communicavit litteris ponere?','Finis diei laeti! Omnes ___ salutant. Primus dies plenus novis amicis erat!'],
  nl: ['Vrienden op de eerste dag','Vandaag is de eerste schooldag! Een klein kind kwam aan met een ___ vol verrassingen.','In de klas staan kleurrijke ___ op elke tafel. Kun je spellen wat je ziet?','Speeltijd! Buiten is er een grote ___ die glanst onder de ___. Wat een dag!','Een nieuwe vriend deelt zijn ___. Wat lief! Kun je spellen wat er gedeeld werd?','Einde van een fijne dag! Iedereen zwaait met ___. De eerste dag zat vol nieuwe vrienden!'],
  pl: ['Przyjaciele pierwszego dnia','Dziś jest pierwszy dzień szkoły! Małe dziecko przyszło z ___ pełnym niespodzianek.','W klasie na każdym stoliku są kolorowe ___. Czy potrafisz przeliterować co widzisz?','Czas na zabawę! Na dworze jest duży ___ lśniący pod ___. Co za dzień!','Nowy przyjaciel dzieli się swoim ___. Jak miło! Czy potrafisz przeliterować czym się podzielił?','Koniec szczęśliwego dnia! Wszyscy machają ___. Pierwszy dzień był pełen nowych przyjaciół!'],
  pt: ['Amigos do primeiro dia','Hoje é o primeiro dia de escola! Uma criança chegou com uma ___ cheia de surpresas.','Na sala de aula tem ___ coloridos em cada mesa. Você sabe soletrar o que vê?','Hora de brincar! Lá fora tem um grande ___ brilhando sob o ___. Que dia!','Um novo amigo compartilha seu ___. Que gentil! Você sabe soletrar o que foi compartilhado?','Fim de um dia feliz! Todos acenam com ___. O primeiro dia foi cheio de novos amigos!'],
  tr: ['İlk Gün Arkadaşları','Bugün okulun ilk günü! Küçük bir çocuk sürprizlerle dolu bir ___ ile geldi.','Sınıfta her masada renkli ___ var. Gördüğünü heceleyebilir misin?','Oyun zamanı! Dışarıda ___\'ın altında parlayan büyük bir ___ var. Ne güzel bir gün!','Yeni bir arkadaş ___\'ını paylaşıyor. Ne tatlı! Paylaşılan şeyi heceleyebilir misin?','Mutlu bir günün sonu! Herkes ___ ile el sallıyor. İlk gün yeni arkadaşlarla doluydu!'],
  zh: ['第一天的朋友','今天是上学的第一天！一个小朋友带着装满惊喜的___来了。','教室里每张桌子上都有彩色的___。你能拼写你看到的东西吗？','游戏时间！外面有一个大大的___在___下面闪闪发光。多棒的一天！','一个新朋友分享了他的___。真好！你能拼写他分享的东西吗？','快乐的一天结束了！大家都在挥着___。第一天充满了新朋友！'],
};

// Story 6: wombatStars
S['wombatStars'] = {
  ar: ['وومبات يعد النجوم','عندما تغيب الشمس خلف التلال، يصعد وومبات إلى مكانه المفضل. ضوء كبير مستدير متوهج يظهر في السماء. ما هو؟','ينظر وومبات للأعلى. ___ صغير يتلألأ في ___. يبدأ في ___!','شكل ناعم رقيق ينجرف عبر السماء، يخفي ضوء القمر للحظة. ما هو؟','عيون وومبات تثقل. لديه أجمل ___. يشعر بالـ___ والأمان، ملفوفاً في ___ مريح.','في حلمه، يلتقي وومبات بصديق ناعم محبوب يعطيه عناقاً دافئاً. يا له من مخلوق ودود!'],
  da: ['Wombat tæller stjernerne','Da solen dykker bag bakkerne, klatrer Wombat op til sit yndlingssted. Et stort rundt lysende lys dukker op på himlen. Hvad er det?','Wombat kigger op. En lille ___ blinker i ___. Den begynder at ___!','En blød, dunblød form driver over himlen og skjuler månelyset et øjeblik. Hvad er det?','Wombats øjne bliver tunge. Han har den mest vidunderlige ___. Han føler sig ___ og tryg, svøbt i en hyggelig ___.','I sin drøm møder Wombat en blød, krammevenlig ven som giver ham et varmt kram. Sikke et venligt væsen!'],
  de: ['Wombat zählt die Sterne','Als die Sonne hinter den Hügeln versinkt, klettert Wombat auf seinen Lieblingsplatz. Ein großes, rundes, leuchtendes Licht erscheint am Himmel. Was ist es?','Wombat schaut nach oben. Ein kleiner ___ funkelt im ___. Es beginnt zu ___!','Eine weiche, flauschige Form treibt über den Himmel und verbirgt das Mondlicht für einen Moment. Was ist es?','Wombats Augen werden schwer. Er hat den wunderbarsten ___. Er fühlt sich ___ und sicher, eingewickelt in ein gemütliches ___.','In seinem Traum trifft Wombat einen weichen, kuschligen Freund, der ihm eine warme Umarmung gibt. Was für ein freundliches Wesen!'],
  es: ['Wombat cuenta las estrellas','Cuando el sol se pone tras las colinas, Wombat sube a su mirador favorito. Una luz grande, redonda y brillante aparece en el cielo. ¿Qué es?','Wombat mira hacia arriba. Una pequeña ___ brilla en el ___. ¡Empieza a ___!','Una forma suave y esponjosa cruza el cielo, ocultando la luz de la luna por un momento. ¿Qué es?','Los ojos de Wombat se ponen pesados. Tiene el más maravilloso ___. Se siente ___ y seguro, envuelto en un acogedor ___.','En su sueño, Wombat conoce a un amigo suave y tierno que le da un abrazo cálido. ¡Qué criatura tan amigable!'],
  fr: ['Wombat compte les étoiles','Quand le soleil se couche derrière les collines, Wombat grimpe à son endroit préféré. Une grande lumière ronde et brillante apparaît dans le ciel. Qu\\\'est-ce que c\\\'est ?','Wombat regarde en haut. Une petite ___ scintille dans le ___. Elle commence à ___ !','Une forme douce et duveteuse dérive dans le ciel, cachant le clair de lune un instant. Qu\\\'est-ce que c\\\'est ?','Les yeux de Wombat deviennent lourds. Il fait le plus merveilleux ___. Il se sent ___ et en sécurité, enveloppé dans un ___ douillet.','Dans son rêve, Wombat rencontre un ami doux et câlin qui lui fait un gros câlin. Quelle créature amicale !'],
  it: ['Wombat conta le stelle','Quando il sole tramonta dietro le colline, Wombat sale al suo punto preferito. Una grande luce rotonda e luminosa appare nel cielo. Cos\\\'è?','Wombat guarda in alto. Una piccola ___ luccica nel ___. Comincia a ___!','Una forma morbida e soffice fluttua nel cielo, nascondendo il chiaro di luna per un momento. Cos\\\'è?','Gli occhi di Wombat si appesantiscono. Ha il più meraviglioso ___. Si sente ___ e al sicuro, avvolto in un accogliente ___.','Nel suo sogno, Wombat incontra un amico morbido e coccoloso che gli dà un abbraccio caldo. Che creatura amichevole!'],
  ja: ['ウォンバットがほしをかぞえる','たいようがおかのむこうにしずむと、ウォンバットはおきにいりのばしょにのぼります。おおきくてまるいひかりがそらにあらわれました。なにかな？','ウォンバットがみあげます。ちいさな___が___のなかできらきらしています。___はじめた！','やわらかくてふわふわのかたちがそらをただよって、つきのひかりをいっしゅんかくします。なにかな？','ウォンバットのめがおもくなります。いちばんすばらしい___をみます。___であんぜんなきもちで、ここちよい___につつまれています。','ゆめのなかで、ウォンバットはやわらかくてだきしめたいともだちにあいます。あたたかいハグをしてくれます。なんてやさしいいきもの！'],
  la: ['Wombat stellas numerat','Cum sol post colles descendit, Wombat ad locum dilectum ascendit. Magna rotunda lucens lux in caelo apparet. Quid est?','Wombat sursum spectat. Parva ___ in ___ scintillat. ___ incipit!','Mollis lanuginosa forma per caelum fluit, lunam momentaneam celans. Quid est?','Oculi Wombat graves fiunt. Mirabilissimum ___ habet. Se ___ et tutum sentit, in commodo ___ involutus.','In somnio, Wombat mollem amicum amplexantem calidum obviam dat. Quam amica creatura!'],
  nl: ['Wombat telt de sterren','Als de zon achter de heuvels zakt, klimt Wombat naar zijn favoriete plek. Een groot, rond, gloeiend licht verschijnt aan de hemel. Wat is het?','Wombat kijkt omhoog. Een klein ___ twinkelt in de ___. Het begint te ___!','Een zachte, donzige vorm drijft over de hemel en verbergt het maanlicht even. Wat is het?','Wombats ogen worden zwaar. Hij heeft de mooiste ___. Hij voelt zich ___ en veilig, gewikkeld in een gezellig ___.','In zijn droom ontmoet Wombat een zacht, knuffelig vriendje dat hem een warme knuffel geeft. Wat een vriendelijk beestje!'],
  pl: ['Wombat liczy gwiazdy','Gdy słońce zachodzi za wzgórzami, Wombat wspina się na swoje ulubione miejsce. Duże, okrągłe, świecące światło pojawia się na niebie. Co to jest?','Wombat patrzy w górę. Mała ___ migocze w ___. Zaczyna ___!','Miękki, puszysty kształt dryfuje po niebie, na chwilę zasłaniając światło księżyca. Co to jest?','Oczy Wombata ciężkieją. Ma najwspanialszy ___. Czuje się ___ i bezpiecznie, owinięty w przytulny ___.','We śnie Wombat spotyka miękkiego, przytulnego przyjaciela, który daje mu ciepły uścisk. Co za przyjazne stworzenie!'],
  pt: ['Wombat conta as estrelas','Quando o sol se põe atrás das colinas, Wombat sobe ao seu lugar favorito. Uma luz grande, redonda e brilhante aparece no céu. O que é?','Wombat olha para cima. Uma pequena ___ brilha no ___. Começa a ___!','Uma forma macia e fofinha flutua pelo céu, escondendo a luz da lua por um momento. O que é?','Os olhos de Wombat ficam pesados. Ele tem o mais maravilhoso ___. Se sente ___ e seguro, enrolado em um aconchegante ___.','No seu sonho, Wombat encontra um amigo macio e fofinho que lhe dá um abraço quentinho. Que criatura amigável!'],
  tr: ['Wombat Yıldızları Sayıyor','Güneş tepelerin arkasına battığında, Wombat en sevdiği yere tırmanır. Gökyüzünde büyük, yuvarlak, parlayan bir ışık belirir. Ne bu?','Wombat yukarı bakar. Küçük bir ___ ___\'da parıldar. ___ başlar!','Yumuşak, kabarık bir şekil gökyüzünde süzülerek ay ışığını bir anlığına gizler. Ne bu?','Wombat\\\'ın gözleri ağırlaşır. En harika ___\'ı görür. Kendini ___ ve güvende hisseder, rahat bir ___\'a sarılır.','Rüyasında Wombat, ona sıcak bir sarılma veren yumuşak, sevimli bir arkadaşla karşılaşır. Ne kadar dostça bir yaratık!'],
  zh: ['袋熊数星星','太阳落到山丘后面，袋熊爬上他最喜欢的地方。天空中出现了一个又大又圆又亮的光。那是什么？','袋熊抬头看。一颗小小的___在___中闪烁。开始___了！','一个柔软蓬松的形状飘过天空，暂时遮住了月光。那是什么？','袋熊的眼睛变得沉重。他做了最美好的___。他感到___和安全，裹在舒适的___里。','在梦里，袋熊遇到了一个柔软可爱的朋友，给了他一个温暖的拥抱。多么友好的小动物！'],
};

// Story 7: jungleWelcome
S['jungleWelcome'] = {
  ar: ['الغابة ترحب بك','تدخل الغابة وتسمع صوت طقطقة لطيف. من بين الأشجار، يظهر مخلوق رائع بعرف متدفق!','على ___، ___ بيضاء رقيقة تقضم ___ في أشعة الشمس!','العشب الطويل يتحرك. أذنان بخطوط سوداء وبيضاء تظهران. يا لها من أنماط مذهلة!','___ لطيف يجلس يأكل ___ عالياً في ___.',   'عالياً في شجرة الكينا، شخص رمادي ورقيق يأخذ قيلولة. تهجّ اسمه!'],
  da: ['Junglen byder dig velkommen','Du træder ind i junglen og hører en blid klip-klap lyd. Gennem træerne dukker et pragtfuldt væsen med en bølgende manke op!','På ___ nipper fluffy hvide ___ i ___!','Det høje græs rasler. To ører med sorte og hvide striber dukker op. Sikke et slående mønster!','En blid ___ sidder og spiser en ___ højt oppe i et ___.','Højt oppe i et eukalyptustræ tager en grå og dunblød en lur. Stav deres navn!'],
  de: ['Der Dschungel heißt dich willkommen','Du betrittst den Dschungel und hörst ein sanftes Klipp-Klapp. Zwischen den Bäumen erscheint ein prächtiges Wesen mit wallender Mähne!','Auf der ___ knabbern flauschige weiße ___ in der Sonne!','Das hohe Gras raschelt. Zwei Ohren mit schwarzweißen Streifen tauchen auf. Was für ein auffälliges Muster!','Ein sanfter ___ sitzt und isst eine ___ hoch oben in einem ___.','Hoch oben in einem Eukalyptusbaum macht jemand Graues und Flauschiges ein Nickerchen. Buchstabiere seinen Namen!'],
  es: ['La selva te da la bienvenida','Entras en la selva y escuchas un suave clip-clop. ¡Entre los árboles aparece una magnífica criatura con una melena ondulante!','¡En el ___, ___ blancas y esponjosas mordisquean ___ bajo el sol!','La hierba alta cruje. Dos orejas con rayas blancas y negras asoman. ¡Qué patrón tan llamativo!','Un ___ gentil se sienta comiendo una ___ en lo alto de un ___.','Arriba en un eucalipto, alguien gris y esponjoso está durmiendo la siesta. ¡Deletrea su nombre!'],
  fr: ['La jungle vous accueille','Tu entres dans la jungle et entends un doux clip-clop. À travers les arbres, une magnifique créature à la crinière flottante apparaît !','Dans le ___, de douces ___ blanches grignotent de l\\\'___ au soleil !','Les hautes herbes bruissent. Deux oreilles à rayures noires et blanches apparaissent. Quel motif saisissant !','Un ___ gentil est assis et mange une ___ tout en haut d\\\'un ___.','Tout en haut d\\\'un eucalyptus, quelqu\\\'un de gris et duveteux fait la sieste. Épelle son nom !'],
  it: ['La giungla ti dà il benvenuto','Entri nella giungla e senti un dolce clip-clop. Tra gli alberi appare una magnifica creatura con una criniera fluente!','Nel ___, soffici ___ bianche mordicchiano ___ al sole!','L\\\'erba alta fruscia. Due orecchie con strisce bianche e nere spuntano. Che motivo sorprendente!','Un ___ gentile siede mangiando una ___ in alto su un ___.','In alto su un eucalipto, qualcuno di grigio e morbido sta facendo un pisolino. Sillabia il suo nome!'],
  ja: ['ジャングルへようこそ','ジャングルにはいると、やさしいパカパカというおとがきこえます。きのあいだから、ながれるたてがみのすばらしいいきものがあらわれました！','___のうえで、ふわふわのしろい___がひなたで___をかじっています！','たかいくさがカサカサなります。くろとしろのしまもようのみみがふたつとびだしました。なんてめだつもようでしょう！','やさしい___が___のたかいところで___をたべてすわっています。','ユーカリのきのたかいところで、はいいろでふわふわのだれかがおひるねしています。なまえをつづろう！'],
  la: ['Silva te salutat','In silvam intras et lenem sonum audis. Per arbores, magnifica creatura cum iuba fluente apparet!','In ___, molles albae ___ in sole ___ rodunt!','Alta herba susurrat. Duae aures cum striis nigris et albis apparent. Quam insignis forma!','Mitis ___ sedens ___ in alto ___ edit.','In alto in arbore eucalypti, aliquis canus et mollis dormitat. Nomen litteris pone!'],
  nl: ['De jungle verwelkomt je','Je stapt de jungle in en hoort een zacht klip-klop geluid. Tussen de bomen verschijnt een prachtig wezen met een wapperende manen!','Op de ___ knabbelen donzige witte ___ aan ___ in de zon!','Het hoge gras ritselt. Twee oren met zwart-witte strepen komen tevoorschijn. Wat een opvallend patroon!','Een lieve ___ zit een ___ te eten hoog in een ___.','Hoog in een eucalyptusboom doet iemand grijs en donzig een dutje. Spel hun naam!'],
  pl: ['Dżungla cię wita','Wchodzisz do dżungli i słyszysz delikatny stukot kopyt. Między drzewami pojawia się wspaniałe stworzenie z powiewającą grzywą!','Na ___ puszyste białe ___ skubią ___ w słońcu!','Wysoka trawa szeleści. Dwa uszy z czarno-białymi paskami wyskakują. Co za uderzający wzór!','Łagodny ___ siedzi jedząc ___ wysoko na ___.','Wysoko na drzewie eukaliptusowym ktoś szary i puszysty drzemie. Przeliteruj imię!'],
  pt: ['A selva te dá as boas-vindas','Você entra na selva e ouve um suave clip-clop. Entre as árvores, uma magnífica criatura com uma crina esvoaçante aparece!','No ___, ___ brancos e fofinhos mordiscam ___ ao sol!','A grama alta farfalha. Duas orelhas com listras pretas e brancas aparecem. Que padrão marcante!','Um ___ gentil está sentado comendo uma ___ no alto de um ___.','Lá no alto de um eucalipto, alguém cinza e fofinho está tirando uma soneca. Soletre o nome!'],
  tr: ['Orman Seni Karşılıyor','Ormana giriyorsun ve nazik bir tıkırtı duyuyorsun. Ağaçların arasından, dalgalanan yeleli muhteşem bir yaratık belirir!','___\'da, kabarık beyaz ___ güneşte ___ kemiriyor!','Uzun otlar hışırdıyor. Siyah beyaz çizgili iki kulak beliriyor. Ne çarpıcı bir desen!','Nazik bir ___ yüksekte bir ___\'da ___ yiyerek oturuyor.','Okaliptüs ağacının tepesinde, gri ve tüylü biri şekerleme yapıyor. İsmini hecele!'],
  zh: ['丛林欢迎你','你走进丛林，听到轻柔的嗒嗒声。树丛间出现了一只有着飘逸鬃毛的壮丽生物！','在___上，毛茸茸的白色___在阳光下啃着___！','高高的草丛沙沙作响。两只黑白条纹的耳朵冒了出来。多么醒目的花纹！','一只温柔的___坐在高高的___上吃着___。','在桉树高处，一个灰色毛茸茸的家伙正在打盹。拼写它的名字！'],
};

// Story 8: bearHungry
S['bearHungry'] = {
  ar: ['بطن الدب الجائع','بطن الدب يقرقر! يفتح باب المطبخ. شيء دافئ وذهبي خرج للتو من الفرن!','في ___، لاحظ الدب ___ من الفاكهة البنفسجية تنمو على ___!','عشاء الدب المفضل في الفرن، مع جبن ذائب يغلي على الوجه!','بوب! بعض ___ قفز من المحمصة، ___ ومقرمش، مثالي مع ___!','للتحلية، يقطف الدب فاكهة حلوة استوائية برتقالية وعصارية من الداخل. يا لها من وليمة!'],
  da: ['Bjørns sultne mave','Bjørns mave rumler! Han åbner køkkendøren. Noget varmt og gyldent er lige kommet ud af ovnen!','I ___ ser Bjørn en ___ med lilla frugt der vokser på en ___!','Bjørns absolutte yndlingsmiddag er i ovnen, med smeltet ost der bobler ovenpå!','Pop! Noget ___ poppede op fra brødristeren, ___ og sprødt, perfekt med ___!','Til dessert plukker Bjørn en sød, tropisk frugt der er orange og saftig indeni. Sikke en fest!'],
  de: ['Bärs hungriger Bauch','Bärs Bauch knurrt! Er öffnet die Küchentür. Etwas Warmes und Goldenes kam gerade aus dem Ofen!','Im ___ entdeckt Bär ein ___ lila Früchte auf einem ___!','Bärs absolutes Lieblingsessen ist im Ofen, mit geschmolzenem Käse der oben blubbert!','Pop! Etwas ___ sprang aus dem Toaster, ___ und knusprig, perfekt mit ___!','Zum Nachtisch pflückt Bär eine süße, tropische Frucht die innen orange und saftig ist. Was für ein Fest!'],
  es: ['La barriguita hambrienta de Oso','¡La barriga de Oso está rugiendo! Abre la puerta de la cocina. ¡Algo cálido y dorado acaba de salir del horno!','¡En el ___, Oso ve un ___ de fruta morada creciendo en un ___!','¡La cena favorita de Oso está en el horno, con queso derretido burbujeando encima!','¡Pop! Algo de ___ saltó de la tostadora, ___ y crujiente, ¡perfecto con ___!','De postre, Oso recoge una fruta dulce y tropical que es naranja y jugosa por dentro. ¡Qué festín!'],
  fr: ['Le ventre affamé d\\\'Ours','Le ventre d\\\'Ours gargouille ! Il ouvre la porte de la cuisine. Quelque chose de chaud et doré vient de sortir du four !','Dans le ___, Ours repère un ___ de fruits violets poussant sur un ___ !','Le dîner préféré d\\\'Ours est dans le four, avec du fromage fondu qui bouillonne !','Pop ! Du ___ a sauté du grille-pain, ___ et croustillant, parfait avec ___ !','Pour le dessert, Ours cueille un fruit doux et tropical qui est orange et juteux à l\\\'intérieur. Quel festin !'],
  it: ['La pancina affamata di Orso','La pancia di Orso brontola! Apre la porta della cucina. Qualcosa di caldo e dorato è appena uscito dal forno!','Nel ___, Orso vede un ___ di frutta viola che cresce su un ___!','La cena preferita di Orso è nel forno, con formaggio fuso che gorgoglia sopra!','Pop! Del ___ è saltato fuori dal tostapane, ___ e croccante, perfetto con ___!','Per dessert, Orso raccoglie un frutto dolce e tropicale arancione e succoso dentro. Che banchetto!'],
  ja: ['くまのおなかがぺこぺこ','くまのおなかがグーグーなっている！だいどころのドアをあけます。あたたかくてきんいろのなにかがオーブンからでてきたよ！','___のなかで、くまは___のむらさきのくだものが___にそだっているのをみつけました！','くまのだいすきなゆうごはんがオーブンのなかに、とけたチーズがぶくぶくのっています！','ポン！___がトースターからとびだした、___でカリカリ、___といっしょにかんぺき！','デザートに、くまはあまくてトロピカルなくだものをえらびます。なかはオレンジいろでジューシー。なんてごちそう！'],
  la: ['Venter esuriens Ursi','Venter Ursi murmurat! Ianuam culinae aperit. Aliquid calidum et aureum modo de furno exiit!','In ___, Ursus ___ fructuum purpureorum in ___ crescentem videt!','Cena dilectissima Ursi in furno est, cum caseo liquefacto supra bulliente!','Pop! Aliquid ___ de torrente panis exsilivit, ___ et fragile, perfectum cum ___!','Pro mensa secunda, Ursus dulcem fructum tropicum qui intus aurantiacus et sucosus est carpit. Quae epulae!'],
  nl: ['Beers hongerige buik','Beers buik rommelt! Hij opent de keukendeur. Iets warms en goudens kwam net uit de oven!','In de ___ ziet Beer een ___ paars fruit groeien aan een ___!','Beers favoriete avondeten staat in de oven, met gesmolten kaas die erboven borrelt!','Pop! Wat ___ sprong uit de broodrooster, ___ en knapperig, perfect met ___!','Als toetje plukt Beer een zoet, tropisch fruit dat van binnen oranje en sappig is. Wat een feest!'],
  pl: ['Głodny brzuszek Misia','Brzuch Misia burczy! Otwiera drzwi kuchni. Coś ciepłego i złotego właśnie wyszło z pieca!','W ___ Miś widzi ___ fioletowych owoców rosnących na ___!','Ulubiona kolacja Misia jest w piekarniku, z rozpuszczonym serem bulgoczącym na wierzchu!','Pop! Trochę ___ wyskoczyło z tostera, ___ i chrupiące, idealne z ___!','Na deser Miś zrywa słodki, tropikalny owoc, który w środku jest pomarańczowy i soczysty. Co za uczta!'],
  pt: ['A barriguinha faminta do Urso','A barriga do Urso está roncando! Ele abre a porta da cozinha. Algo quente e dourado acabou de sair do forno!','No ___, Urso vê um ___ de frutas roxas crescendo em um ___!','O jantar favorito do Urso está no forno, com queijo derretido borbulhando por cima!','Pop! Um pouco de ___ saltou da torradeira, ___ e crocante, perfeito com ___!','De sobremesa, Urso pega uma fruta doce e tropical que é laranja e suculenta por dentro. Que banquete!'],
  tr: ['Ayının Aç Karnı','Ayının karnı gurulduyor! Mutfak kapısını açıyor. Fırından sıcak ve altın rengi bir şey çıktı!','___\'da Ayı, ___\'da yetişen bir ___ mor meyve görüyor!','Ayının en sevdiği yemek fırında, üstünde erimiş peynir fokurdayarak!','Pop! Biraz ___ tost makinesinden fırladı, ___ ve çıtır, ___ ile mükemmel!','Tatlı olarak Ayı tatlı, tropik bir meyve toplar — içi turuncu ve sulu. Ne güzel bir ziyafet!'],
  zh: ['小熊的饿肚子','小熊的肚子咕咕叫！他打开厨房门。温暖金黄的东西刚从烤箱里出来！','在___里，小熊看到一___紫色水果长在___上！','小熊最爱的晚餐在烤箱里，融化的奶酪在上面冒泡！','砰！一些___从烤面包机里弹出来，___又脆，配___完美！','甜点时间，小熊摘了一个甜甜的热带水果，里面是橙色多汁的。好丰盛的大餐！'],
};

// Story 9: enchantedCastle
S['enchantedCastle'] = {
  ar: ['القلعة المسحورة','فتحت كتاب قصص سحري وسُحبت إلى الداخل! أمامك مبنى عظيم بأبراج عالية. ما هو؟','في الداخل، ___ ودود بقشور لامعة يرحب بك. ينفث ___ دافئاً، لكن لا تقلق، إنه ___!','المخلوق يقودك إلى قاعة العرش، حيث أحكم وألطف حاكم في كل الأرض يبتسم بدفء.','لإيجاد طريق العودة، اعبر ___. اتبع ___ عبر ___ المرقط.','في قلب كل شيء، دوامة من الشرارات تظهر. الكتاب يتوهج. هذه القوة ستأخذك إلى المنزل!'],
  da: ['Det fortryllede slot','Du åbner en magisk historiebog og trækkes lige ind! Foran dig står en storslået bygning med høje tårne. Hvad er det?','Indeni hilser en venlig ___ med glimtende skæl på dig. Den puster varm ___, men rolig, den er ___!','Væsnet fører dig til tronsalen, hvor den klogeste og venligste hersker i hele landet smiler varmt.','For at finde hjem, rejs gennem ___. Følg ___ gennem det plettet ___.','I hjertet af det hele dukker en hvirvel af gnister op. Bogen lyser. Denne kraft vil tage dig hjem!'],
  de: ['Die verzauberte Burg','Du öffnest ein magisches Märchenbuch und wirst hineingezogen! Vor dir steht ein prächtiges Gebäude mit hohen Türmen. Was ist es?','Drinnen begrüßt dich ein freundlicher ___ mit schimmernden Schuppen. Er atmet warmes ___, aber keine Sorge, es ist ___!','Das Wesen führt dich zum Thronsaal, wo der weiseste und freundlichste Herrscher des ganzen Landes warm lächelt.','Um nach Hause zu finden, reise durch den ___. Folge dem ___ durch das gefleckte ___.','Im Herzen von allem erscheint ein Wirbel von Funken. Das Buch leuchtet. Diese Kraft bringt dich nach Hause!'],
  es: ['El castillo encantado','¡Abres un libro de cuentos mágico y te absorbe! Ante ti se alza un edificio grandioso con torres altas. ¿Qué es?','Dentro, un ___ amigable con escamas brillantes te saluda. Respira ___ cálido, ¡pero no te preocupes, es ___!','La criatura te lleva a la sala del trono, donde el gobernante más sabio y amable de toda la tierra sonríe cálidamente.','Para encontrar el camino a casa, viaja por el ___. Sigue el ___ por el ___ moteado.','En el corazón de todo, aparece un remolino de destellos. El libro brilla. ¡Este poder te llevará a casa!'],
  fr: ['Le château enchanté','Tu ouvres un livre de contes magique et tu es aspiré dedans ! Devant toi se dresse un grand bâtiment avec de hautes tours. Qu\\\'est-ce que c\\\'est ?','À l\\\'intérieur, un ___ amical aux écailles chatoyantes t\\\'accueille. Il souffle du ___ chaud, mais ne t\\\'inquiète pas, il est ___ !','La créature te conduit à la salle du trône, où le souverain le plus sage et le plus gentil sourit chaleureusement.','Pour trouver ton chemin, voyage à travers le ___. Suis le ___ à travers le ___ tacheté.','Au cœur de tout, un tourbillon d\\\'étincelles apparaît. Le livre brille. Ce pouvoir te ramènera chez toi !'],
  it: ['Il castello incantato','Apri un libro di fiabe magico e vieni risucchiato dentro! Davanti a te si erge un grande edificio con alte torri. Cos\\\'è?','Dentro, un ___ amichevole con squame luccicanti ti saluta. Soffia ___ caldo, ma non preoccuparti, è ___!','La creatura ti conduce alla sala del trono, dove il sovrano più saggio e gentile di tutta la terra sorride calorosamente.','Per trovare la via di casa, attraversa il ___. Segui il ___ attraverso il ___ screziato.','Nel cuore di tutto, appare un vortice di scintille. Il libro risplende. Questo potere ti porterà a casa!'],
  ja: ['まほうのおしろ','まほうのえほんをひらくと、なかにすいこまれた！めのまえに、たかいとうのあるりっぱなたてものがあります。なにかな？','なかでは、きらきらのうろこをもったやさしい___がむかえてくれます。あたたかい___をふきますが、しんぱいしないで、___だよ！','そのいきものがおうざのまにつれていきます。いちばんかしこくてやさしいおさまがにこにこしています。','おうちへのみちをみつけるには、___をたびしよう。まだらな___をとおって___についていこう。','すべてのちゅうしんに、きらめきのうずがあらわれます。えほんがひかります。このちからがおうちにつれてかえってくれる！'],
  la: ['Arx Incantata','Librum fabulosum magicum aperis et intus traharis! Ante te stat magnificum aedificium cum altis turribus. Quid est?','Intus, amicabilis ___ squamis fulgens te salutat. Calidum ___ spirat, sed noli timere, ___ est!','Creatura te ad aulam throni ducit, ubi sapientissimus et benignissimus rector totius terrae blande subridet.','Ut viam domum invenias, per ___ iter fac. ___ per maculatum ___ sequere.','In corde omnium, vortex scintillarum apparet. Liber lucet. Haec vis te domum feret!'],
  nl: ['Het betoverde kasteel','Je opent een magisch sprookjesboek en wordt er recht in getrokken! Voor je staat een groots gebouw met hoge torens. Wat is het?','Binnen begroet een vriendelijke ___ met glinsterende schubben je. Het blaast warme ___, maar maak je geen zorgen, het is ___!','Het wezen leidt je naar de troonzaal, waar de wijste en vriendelijkste heerser van het hele land warm glimlacht.','Om de weg naar huis te vinden, reis door het ___. Volg de ___ door het gevlekte ___.','In het hart van alles verschijnt een werveling van vonken. Het boek gloeit. Deze kracht brengt je naar huis!'],
  pl: ['Zaczarowany zamek','Otwierasz magiczną księgę i zostajesz wciągnięty do środka! Przed tobą stoi wspaniały budynek z wysokimi wieżami. Co to jest?','Wewnątrz wita cię przyjazny ___ z błyszczącymi łuskami. Zieje ciepłym ___, ale nie martw się, jest ___!','Stworzenie prowadzi cię do sali tronowej, gdzie najmądrzejszy i najżyczliwszy władca ciepło się uśmiecha.','Aby znaleźć drogę do domu, podróżuj przez ___. Podążaj za ___ przez cętkowany ___.','W sercu wszystkiego pojawia się wir iskier. Księga świeci. Ta moc zabierze cię do domu!'],
  pt: ['O castelo encantado','Você abre um livro de contos mágico e é puxado para dentro! Diante de você está um grande edifício com torres altas. O que é?','Dentro, um ___ amigável com escamas brilhantes te cumprimenta. Ele sopra ___ quente, mas não se preocupe, é ___!','A criatura te leva à sala do trono, onde o governante mais sábio e gentil de toda a terra sorri calorosamente.','Para encontrar o caminho de casa, viaje pelo ___. Siga o ___ pelo ___ salpicado.','No coração de tudo, um redemoinho de brilhos aparece. O livro brilha. Esse poder vai te levar para casa!'],
  tr: ['Büyülü Kale','Sihirli bir hikâye kitabı açıyorsun ve içine çekiliyorsun! Önünde yüksek kuleleri olan büyük bir bina duruyor. Ne bu?','İçeride, parlak pullu dostça bir ___ seni karşılıyor. Sıcak ___ üflüyor ama endişelenme, o ___!','Yaratık seni taht odasına götürüyor, tüm ülkenin en bilge ve en nazik hükümdarı sıcacık gülümsüyor.','Eve dönüş yolunu bulmak için ___\'dan geç. Benekli ___\'dan ___ takip et.','Her şeyin kalbinde, bir pırıltı girdabı belirir. Kitap parlıyor. Bu güç seni eve götürecek!'],
  zh: ['魔法城堡','你打开一本魔法故事书，被吸了进去！面前矗立着一座有高塔的宏伟建筑。它是什么？','里面，一只有闪亮鳞片的友好___迎接你。它吐出温暖的___，但别担心，它是___的！','这个生物带你来到王座大厅，最聪明最善良的统治者温暖地微笑着。','要找到回家的路，穿过___。跟着___穿过斑驳的___。','在一切的中心，一阵闪光旋涡出现了。书发出光芒。这股力量会带你回家！'],
};

// Story 10: farmyardFriends
S['farmyardFriends'] = {
  ar: ['أصدقاء المزرعة','بوابة المزرعة تفتح! صديق كبير مرقط يمضغ العشب. هل تستطيع تهجئة اسمه؟','في ___، ___ متسلل يطل!','طنين! زائر صغير مخطط يحط على زهرة.','خلف الحظيرة، ___ يضع ___!','صديق المزارع الوردي الموحل يتراشق في البركة. تهجّ اسمه!'],
  da: ['Gårdvenner','Gårdlågen åbner! En stor plettet ven tygger græs. Kan du stave deres navn?','I ___ kigger en lusket ___ ud!','Buzz buzz! En lille stribet gæst lander på en blomst.','Bag laden lægger ___ et ___!','Bondens mudrede lyserøde ven plasker i vandpytten. Stav deres navn!'],
  de: ['Bauernhoffreunde','Das Hoftor öffnet sich! Ein großer gefleckter Freund kaut das Gras. Kannst du den Namen buchstabieren?','Im ___ schaut ein heimlicher ___ heraus!','Summ summ! Ein kleiner gestreifter Besucher landet auf einer Blume.','Hinter der Scheune legt der ___ ein ___!','Der schlammige rosa Freund des Bauern planscht in der Pfütze. Buchstabiere seinen Namen!'],
  es: ['Amigos de la granja','¡Se abre la puerta de la granja! Un gran amigo manchado mastica la hierba. ¿Puedes deletrear su nombre?','¡En el ___, un ___ escurridizo asoma!','¡Buzz buzz! Un pequeño visitante rayado aterriza en una flor.','¡Detrás del granero, el ___ pone un ___!','¡El amigo rosado y embarrado del granjero chapotea en el charco. Deletrea su nombre!'],
  fr: ['Amis de la ferme','Le portail de la ferme s\\\'ouvre ! Un grand ami tacheté mâche l\\\'herbe. Peux-tu épeler son nom ?','Dans le ___, un ___ sournois jette un coup d\\\'œil !','Bzz bzz ! Un petit visiteur rayé atterrit sur une fleur.','Derrière la grange, le ___ pond un ___ !','L\\\'ami rose et boueux du fermier éclabousse dans la flaque. Épelle son nom !'],
  it: ['Amici della fattoria','Il cancello della fattoria si apre! Un grande amico maculato mastica l\\\'erba. Sai sillabare il suo nome?','Nel ___, un ___ furtivo sbircia fuori!','Buzz buzz! Un piccolo visitatore a strisce atterra su un fiore.','Dietro il fienile, il ___ depone un ___!','L\\\'amico rosa e fangoso del contadino sguazza nella pozzanghera. Sillabia il suo nome!'],
  ja: ['のうじょうのなかまたち','のうじょうのもんがひらきました！おおきなまだらのなかまがくさをかんでいます。なまえをつづれるかな？','___のなかで、こっそり___がのぞいている！','ブンブン！ちいさなしまもようのおきゃくさんがはなにとまりました。','のうやのうしろで、___が___をうんだ！','のうかのどろだらけのピンクのなかまがみずたまりでバシャバシャ。なまえをつづろう！'],
  la: ['Amici villae','Porta villae aperitur! Magnus maculosus amicus herbam manducat. Potesne nomen litteris ponere?','In ___, furtivus ___ prospicit!','Buzz buzz! Parvus striatus visitator in flore considit.','Post horreum, ___ ovum ___!','Amicus roseus lutulentus agricolae in stagno pluit. Nomen littera!'],
  nl: ['Boerderijvrienden','Het erf gaat open! Een grote gevlekte vriend kauwt op het gras. Kun je de naam spellen?','In het ___ gluurt een stiekeme ___ naar buiten!','Bzzz bzzz! Een klein gestreept bezoekertje landt op een bloem.','Achter de schuur legt de ___ een ___!','De modderige roze vriend van de boer spettert in de plas. Spel de naam!'],
  pl: ['Przyjaciele z podwórka','Brama zagrody się otwiera! Duży nakrapiany przyjaciel żuje trawę. Czy potrafisz przeliterować imię?','W ___ podstępny ___ wygląda!','Bzzz! Mały pasiasty gość ląduje na kwiatku.','Za stodołą ___ składa ___!','Różowy, błotnisty przyjaciel rolnika pluska w kałuży. Przeliteruj imię!'],
  pt: ['Amigos da fazenda','O portão da fazenda se abre! Um grande amigo manchado mastiga a grama. Você sabe soletrar o nome?','No ___, um ___ sorrateiro espia!','Buzz buzz! Um pequeno visitante listrado pousa em uma flor.','Atrás do celeiro, o ___ bota um ___!','O amigo rosado e enlameado do fazendeiro espirra na poça. Soletre o nome!'],
  tr: ['Çiftlik Arkadaşları','Çiftlik kapısı açılıyor! Benekli büyük bir arkadaş ot çiğniyor. İsmini heceleyebilir misin?','___\'da sinsi bir ___ dışarı bakıyor!','Vızz vızz! Küçük çizgili bir misafir bir çiçeğe konuyor.','Ahırın arkasında ___ bir ___ bırakıyor!','Çiftçinin çamurlu pembe arkadaşı su birikintisinde sıçrıyor. İsmini hecele!'],
  zh: ['农场朋友','农场的门开了！一个大大的有斑点的朋友在嚼草。你能拼写它的名字吗？','在___里，一个偷偷摸摸的___探出头来！','嗡嗡！一个小小的条纹访客停在花上。','谷仓后面，___下了一个___！','农夫泥巴巴的粉色朋友在水坑里扑通扑通。拼写它的名字！'],
};

// Story 11: bugHunt
S['bugHunt'] = {
  ar: ['صيد الحشرات','سنذهب لصيد الحشرات! صديق طنان يحط على يدك.','تحت ___، ___ صغير يحمل ورقة!','هو هو! في أعلى الشجرة، طائر حكيم يراقب.','___ أحمر رقيق يندفع إلى ___!','صديقك الوفي ينتظر عند بوابة الحديقة يهز ذيله!'],
  da: ['Insektjagt','Vi tager på insektjagt! En summende ven lander på din hånd.','Under ___ bærer en lille ___ et blad!','Uhu! Oppe i træet kigger en klog fugl.','En fluffy rød ___ suser forbi til ___!','Din trofaste ven venter ved havelågen og logrer med halen!'],
  de: ['Käferjagd','Wir gehen auf Käferjagd! Ein summender Freund landet auf deiner Hand.','Unter dem ___ trägt ein kleiner ___ ein Blatt!','Schuhu! Oben im Baum beobachtet ein weiser Vogel.','Ein flauschiger roter ___ flitzt vorbei zum ___!','Dein treuer Freund wartet am Gartentor und wedelt mit dem Schwanz!'],
  es: ['Caza de bichos','¡Vamos a cazar bichos! Un amigo zumbador aterriza en tu mano.','¡Debajo del ___, un pequeño ___ lleva una hoja!','¡Uh-uh! Arriba en el árbol, un pájaro sabio observa.','¡Un ___ rojo y esponjoso pasa corriendo hacia ___!','¡Tu fiel amigo espera en la puerta del jardín, moviendo la cola!'],
  fr: ['Chasse aux insectes','On part à la chasse aux insectes ! Un ami bourdonnant atterrit sur ta main.','Sous le ___, un petit ___ porte une feuille !','Hou-hou ! En haut de l\\\'arbre, un oiseau sage observe.','Un ___ rouge duveteux passe en courant vers ___ !','Ton fidèle ami attend au portail du jardin en remuant la queue !'],
  it: ['Caccia agli insetti','Andiamo a caccia di insetti! Un amico ronzante atterra sulla tua mano.','Sotto il ___, un piccolo ___ porta una foglia!','Uh-uh! In cima all\\\'albero, un uccello saggio osserva.','Un ___ rosso soffice corre verso ___!','Il tuo fedele amico aspetta al cancello del giardino scodinzolando!'],
  ja: ['むしさがし','むしさがしにいこう！ブンブンいうともだちがてのひらにとまりました。','___のしたで、ちいさな___がはっぱをはこんでいる！','ホーホー！きのうえで、かしこいとりがみています。','ふわふわのあかい___が___にむかってかけていく！','しんじつなともだちがにわのもんでしっぽをふってまっています！'],
  la: ['Venatio Insectorum','Venationem insectorum facimus! Amicus bombilans in manu tua considit.','Sub ___, parvus ___ folium fert!','Bubo! In arbore, sapiens avis spectat.','Mollis ruber ___ ad ___ currit!','Fidelis amicus tuus ad portam horti caudam agitans exspectat!'],
  nl: ['Insectenjacht','We gaan op insectenjacht! Een zoemend vriendje landt op je hand.','Onder de ___ draagt een klein ___ een blaadje!','Oehoe! Boven in de boom kijkt een wijze vogel toe.','Een donzig rood ___ rent naar ___ toe!','Je trouwe vriend wacht bij het tuinhek en kwispelt!'],
  pl: ['Polowanie na robaki','Idziemy na polowanie na robaki! Bzyczący przyjaciel ląduje na twojej dłoni.','Pod ___ mały ___ niesie listek!','Hu-hu! Na drzewie mądry ptak obserwuje.','Puszysty czerwony ___ pędzi do ___!','Twój wierny przyjaciel czeka przy bramie ogrodu machając ogonem!'],
  pt: ['Caça aos bichinhos','Vamos caçar bichinhos! Um amigo zumbidor pousa na sua mão.','Embaixo do ___, um pequeno ___ carrega uma folha!','Uhu! Lá em cima na árvore, um pássaro sábio observa.','Um ___ vermelho fofinho passa correndo para ___!','Seu fiel amigo espera no portão do jardim abanando o rabo!'],
  tr: ['Böcek Avı','Böcek avına çıkıyoruz! Vızıldayan bir arkadaş eline konuyor.','___\'ın altında küçük bir ___ yaprak taşıyor!','Hu-hu! Ağacın tepesinde bilge bir kuş izliyor.','Kabarık kırmızı bir ___ ___\'a koşuyor!','Sadık arkadaşın bahçe kapısında kuyruğunu sallayarak bekliyor!'],
  zh: ['虫虫大搜索','我们去找虫虫！一个嗡嗡的朋友停在你手上。','在___下面，一只小___正搬着一片叶子！','呼呼！树上一只聪明的鸟在看着。','一只毛茸茸的红色___跑向___！','你忠实的朋友在花园门口摇着尾巴等你！'],
};

// Story 12: pondLife
S['pondLife'] = {
  ar: ['حياة البركة','بجانب البركة، ذيل أحمر رقيق يختفي في الشجيرات!','عبر الحقل، ___ يقول ___!','أوينك أوينك! صديق موحل يتدحرج في الأرض الرطبة بجانب البركة.','___ يبدأ في ___!','صديق ناعم فروي يخرخر على الممر المشمس. تهجّ اسمه!'],
  da: ['Liv ved dammen','Nede ved dammen forsvinder en rød fluffy hale ind i buskene!','Over marken siger ___ ___!','Øf øf! En mudret ven ruller i den våde jord ved dammen.','___ begynder at ___!','En blød pelset ven spinder på den solrige sti. Stav deres navn!'],
  de: ['Leben am Teich','Am Teich verschwindet ein flauschiger roter Schwanz in den Büschen!','Über das Feld sagt der ___ ___!','Oink oink! Ein schlammiger Freund wälzt sich im nassen Boden am Teich.','Der ___ fängt an zu ___!','Ein weicher, pelziger Freund schnurrt auf dem sonnigen Weg. Buchstabiere den Namen!'],
  es: ['Vida del estanque','¡Junto al estanque, una cola roja y esponjosa desaparece en los arbustos!','Al otro lado del campo, ¡el ___ dice ___!','¡Oink oink! Un amigo embarrado rueda en el suelo mojado junto al estanque.','¡El ___ empieza a ___!','Un amigo suave y peludo ronronea en el camino soleado. ¡Deletrea su nombre!'],
  fr: ['Vie de l\\\'étang','Au bord de l\\\'étang, une queue rouge duveteuse disparaît dans les buissons !','De l\\\'autre côté du champ, le ___ dit ___ !','Groin groin ! Un ami boueux roule dans la terre humide près de l\\\'étang.','Le ___ commence à ___ !','Un ami doux et poilu ronronne sur le chemin ensoleillé. Épelle son nom !'],
  it: ['Vita dello stagno','Vicino allo stagno, una coda rossa e soffice scompare nei cespugli!','Dall\\\'altra parte del campo, il ___ dice ___!','Oink oink! Un amico fangoso rotola nel terreno bagnato vicino allo stagno.','Il ___ inizia a ___!','Un amico morbido e peloso fa le fusa sul sentiero soleggiato. Sillabia il suo nome!'],
  ja: ['いけのいきもの','いけのそばで、ふわふわのあかいしっぽがやぶのなかにきえていく！','のはらのむこうで、___が___といいます！','ブーブー！どろんこのなかまがいけのそばのぬれたじめんでころがっています。','___が___しはじめた！','やわらかくてもふもふのなかまがひなたのこみちでゴロゴロいっています。なまえをつづろう！'],
  la: ['Vita stagni','Ad stagnum, mollis rubra cauda in frutices evanescit!','Trans campum, ___ dicit ___!','Oink oink! Lutulentus amicus in terra humida ad stagnum volvitur.','___ incipit ___!','Mollis villosus amicus in via aprica murmurans. Nomen littera!'],
  nl: ['Vijverleven','Bij de vijver verdwijnt een donzige rode staart in de struiken!','Over het veld zegt de ___ ___!','Knor knor! Een modderig vriendje rolt in de natte grond bij de vijver.','De ___ begint te ___!','Een zacht harig vriendje spint op het zonnige pad. Spel de naam!'],
  pl: ['Życie nad stawem','Nad stawem puszysty czerwony ogon znika w krzakach!','Na polu ___ mówi ___!','Chrum chrum! Błotnisty przyjaciel turlą się po mokrej ziemi przy stawie.','___ zaczyna ___!','Miękki futrzany przyjaciel mruczy na słonecznej ścieżce. Przeliteruj imię!'],
  pt: ['Vida na lagoa','Na beira da lagoa, um rabo vermelho fofinho desaparece nos arbustos!','Do outro lado do campo, o ___ diz ___!','Oinc oinc! Um amigo enlameado rola no chão molhado perto da lagoa.','O ___ começa a ___!','Um amigo macio e peludo ronrona no caminho ensolarado. Soletre o nome!'],
  tr: ['Gölet Yaşamı','Göletin yanında, kabarık kırmızı bir kuyruk çalılıklarda kayboluyor!','Tarlanın karşısında ___ ___ diyor!','Oink oink! Çamurlu bir arkadaş göletin yanındaki ıslak toprakta yuvarlanıyor.','___ ___\'a başlıyor!','Güneşli patikada yumuşak tüylü bir arkadaş mırıldanıyor. İsmini hecele!'],
  zh: ['池塘生活','在池塘边，一条毛茸茸的红色尾巴消失在灌木丛中！','田野那边，___说___！','哼哼！一个泥巴巴的朋友在池塘边的湿地上打滚。','___开始___了！','一个柔软毛茸茸的朋友在阳光小路上呼噜呼噜。拼写它的名字！'],
};

// Story 13: barnDance
S['barnDance'] = {
  ar: ['رقص الحظيرة','الحظيرة جاهزة للرقص! صديق ذو ريش أحمر يتبختر أولاً.','بعد ذلك، ___ ينزلق عبر ___!','موو! راقص كبير مرقط ينضم للحفلة.','من العوارض، ___ ينادي ___!','آخر راقص لديه ذيل كثيف جميل. من هو؟'],
  da: ['Ladedans','Laden er klar til dans! En rødfjeret ven spankulerer ind først.','Næste glider ___ gennem ___!','Muh! En stor plettet danser slutter sig til festen.','Fra bjælkerne kalder ___ ___!','Den sidste danser har en smuk busket hale. Hvem er det?'],
  de: ['Scheunentanz','Die Scheune ist bereit zum Tanzen! Ein rotgefiederter Freund stolziert zuerst herein.','Als nächstes gleitet der ___ durch den ___!','Muh! Ein großer gefleckter Tänzer kommt zur Party.','Von den Dachsparren ruft der ___ ___!','Der letzte Tänzer hat einen wunderschönen buschigen Schwanz. Wer ist es?'],
  es: ['Baile en el granero','¡El granero está listo para bailar! Un amigo de plumas rojas entra primero.','¡Luego, el ___ se desliza por el ___!','¡Muu! Un gran bailarín manchado se une a la fiesta.','¡Desde las vigas, el ___ llama ___!','El último bailarín tiene una hermosa cola frondosa. ¿Quién es?'],
  fr: ['Bal de la grange','La grange est prête pour le bal ! Un ami à plumes rouges entre en premier.','Ensuite, le ___ glisse à travers le ___ !','Meuh ! Un grand danseur tacheté rejoint la fête.','Depuis les poutres, le ___ appelle ___ !','Le dernier danseur a une magnifique queue touffue. Qui est-ce ?'],
  it: ['Ballo nel fienile','Il fienile è pronto per il ballo! Un amico dalle piume rosse entra per primo.','Poi, il ___ scivola attraverso il ___!','Muuu! Un grande ballerino maculato si unisce alla festa.','Dalle travi, il ___ chiama ___!','L\\\'ultimo ballerino ha una bellissima coda folta. Chi è?'],
  ja: ['のうやのダンス','のうやはダンスのじゅんびができました！あかいはねのなかまがさいしょにはいってきます。','つぎに、___が___をすべりぬけます！','モー！おおきなまだらのダンサーがパーティーにさんかします。','はりのうえから、___が___とよびます！','さいごのダンサーはきれいなふさふさのしっぽをもっています。だれかな？'],
  la: ['Saltatio horrei','Horreum ad saltandum paratum est! Amicus rubris plumis primus ingreditur.','Deinde, ___ per ___ labitur!','Mu! Magnus maculosus saltator conventui se adiungit.','E trabibus, ___ vocat ___!','Ultimus saltator pulchram caudam densam habet. Quis est?'],
  nl: ['Schuurdans','De schuur is klaar voor het dansen! Een roodgevederd vriendje stapt als eerste naar binnen.','Daarna glijdt de ___ door de ___!','Boe! Een grote gevlekte danser doet mee aan het feest.','Vanaf de balken roept de ___ ___!','De laatste danser heeft een prachtige borstelige staart. Wie is het?'],
  pl: ['Taniec w stodole','Stodoła jest gotowa na taniec! Przyjaciel z czerwonymi piórami wkracza pierwszy.','Potem ___ prześlizguje się przez ___!','Muuu! Duży nakrapiany tancerz dołącza do zabawy.','Z belek ___ woła ___!','Ostatni tancerz ma piękny puszysty ogon. Kto to jest?'],
  pt: ['Dança no celeiro','O celeiro está pronto para dançar! Um amigo de penas vermelhas entra primeiro.','Depois, o ___ desliza pelo ___!','Muuu! Um grande dançarino manchado se junta à festa.','Das vigas, o ___ chama ___!','O último dançarino tem uma bela cauda espessa. Quem é?'],
  tr: ['Ahır Dansı','Ahır dansa hazır! Kırmızı tüylü bir arkadaş ilk giriyor.','Sonra ___ ___\'dan kayıyor!','Möö! Benekli büyük bir dansçı partiye katılıyor.','Kirişlerden ___ ___ diye sesleniyor!','Son dansçının güzel gür bir kuyruğu var. Kim o?'],
  zh: ['谷仓舞会','谷仓准备好跳舞了！一个红色羽毛的朋友第一个走进来。','接下来，___从___滑过！','哞！一个大大的有斑点的舞者加入了派对。','从横梁上，___喊着___！','最后一个舞者有漂亮的蓬松尾巴。是谁呢？'],
};

// Story 14: kitchenAdventure
S['kitchenAdventure'] = {
  ar: ['مغامرة المطبخ','وقت الفطور! تحتاج شيئاً تشرب منه. ماذا تحتاج؟','___ يصب ___.',  'بسرعة! ضع أغراضك في شيء تحمله على كتفك!','___ يلبس ___.','بعد يوم حافل، تصعد إلى شيء ناعم ومريح.'],
  da: ['Køkkeneventyr','Tid til morgenmad! Du har brug for noget at drikke af. Hvad har du brug for?','___ hælder ___.',  'Hurtigt! Pak dine ting i noget du bærer på skulderen!','___ tager en ___ på.','Efter en travl dag kravler du op i noget blødt og hyggeligt.'],
  de: ['Küchenabenteuer','Frühstückszeit! Du brauchst etwas zum Trinken. Was brauchst du?','___ gießt den ___.',  'Schnell! Pack deine Sachen in etwas, das du auf der Schulter trägst!','___ zieht ein ___ an.','Nach einem geschäftigen Tag kletterst du in etwas Weiches und Gemütliches.'],
  es: ['Aventura en la cocina','¡Hora del desayuno! Necesitas algo para beber. ¿Qué necesitas?','___ sirve el ___.',  '¡Rápido! ¡Mete tus cosas en algo que llevas al hombro!','___ se pone un ___.','Después de un día ajetreado, te metes en algo suave y acogedor.'],
  fr: ['Aventure en cuisine','L\\\'heure du petit-déjeuner ! Tu as besoin de quelque chose pour boire. De quoi as-tu besoin ?','___ verse le ___.',  'Vite ! Range tes affaires dans quelque chose que tu portes sur l\\\'épaule !','___ met un ___.','Après une journée bien remplie, tu grimpes dans quelque chose de doux et douillet.'],
  it: ['Avventura in cucina','Ora di colazione! Ti serve qualcosa da cui bere. Di cosa hai bisogno?','___ versa il ___.',  'Presto! Metti le tue cose in qualcosa che porti sulla spalla!','___ si mette un ___.','Dopo una giornata intensa, ti arrampichi in qualcosa di morbido e accogliente.'],
  ja: ['だいどころのぼうけん','あさごはんのじかん！のみものをいれるものがひつよう。なにがいるかな？','___が___をそそぐ。','いそいで！かたにかけるものにもちものをいれよう！','___が___をきる。','いそがしいいちにちのあと、やわらかくてここちよいものにもぐりこむ。'],
  la: ['Adventus culinae','Tempus ientaculi! Aliquid ad bibendum opus est. Quid opus est?','___ fundit ___.',  'Cito! Res tuas in aliquid quod in umero fers pone!','___ induit ___.','Post diem plenum, in aliquid molle et commodum ascendis.'],
  nl: ['Keukenavontuur','Tijd voor ontbijt! Je hebt iets nodig om uit te drinken. Wat heb je nodig?','___ schenkt de ___.',  'Snel! Stop je spullen in iets dat je op je schouder draagt!','___ trekt een ___ aan.','Na een drukke dag kruip je in iets zachts en gezellig.'],
  pl: ['Przygoda w kuchni','Czas na śniadanie! Potrzebujesz czegoś do picia. Czego potrzebujesz?','___ nalewa ___.',  'Szybko! Spakuj rzeczy w coś, co nosisz na ramieniu!','___ zakłada ___.','Po pracowitym dniu wchodzisz w coś miękkiego i przytulnego.'],
  pt: ['Aventura na cozinha','Hora do café da manhã! Você precisa de algo para beber. Do que precisa?','___ serve o ___.',  'Rápido! Coloque suas coisas em algo que carrega no ombro!','___ coloca um ___.','Depois de um dia agitado, você sobe em algo macio e aconchegante.'],
  tr: ['Mutfak Macerası','Kahvaltı zamanı! İçecek bir şeye ihtiyacın var. Neye ihtiyacın var?','___ ___\\\'ı döküyor.',  'Çabuk! Eşyalarını omzuna taşıyacağın bir şeye koy!','___ bir ___ giyiyor.','Yoğun bir günün ardından yumuşak ve rahat bir şeye tırmanıyorsun.'],
  zh: ['厨房大冒险','早餐时间！你需要一个喝东西的杯子。你需要什么？','___倒了___。','快！把东西放进你肩上背的包里！','___穿上了___。','忙碌的一天结束后，你爬进柔软舒适的东西里。'],
};

// Story 15: parkDay
S['parkDay'] = {
  ar: ['يوم الحديقة','يا له من يوم جميل! الشيء الكبير الدافئ يلمع في السماء.','إنه ___ جداً! خذ ___.',  'ها هو قادم، يزمجر في الطريق! اقفز!','لا تنسَ ___، ___!','من ينتظر عند بوابة الحديقة بابتسامة كبيرة؟'],
  da: ['Parkdag','Sikke en dejlig dag! Den store varme ting skinner oppe på himlen.','Det er så ___! Tag din ___.',  'Her kommer den, bumlende ned ad vejen! Hop på!','Glem ikke din ___, ___!','Hvem venter ved parklågen med et stort smil?'],
  de: ['Parktag','Was für ein schöner Tag! Das große warme Ding scheint am Himmel.','Es ist so ___! Nimm deinen ___.',  'Da kommt es, rumpelnd die Straße entlang! Spring rauf!','Vergiss nicht dein ___, ___!','Wer wartet am Parktor mit einem großen Lächeln?'],
  es: ['Día en el parque','¡Qué día tan bonito! La cosa grande y cálida brilla en el cielo.','¡Hace tanto ___! Coge tu ___.',  '¡Ahí viene, retumbando por la calle! ¡Sube!','¡No olvides tu ___, ___!','¿Quién espera en la puerta del parque con una gran sonrisa?'],
  fr: ['Jour au parc','Quelle belle journée ! La grande chose chaude brille dans le ciel.','Il fait tellement ___ ! Prends ton ___.',  'Le voilà qui arrive en grondant ! Monte !','N\\\'oublie pas ton ___, ___ !','Qui attend au portail du parc avec un grand sourire ?'],
  it: ['Giornata al parco','Che bella giornata! La grande cosa calda brilla nel cielo.','Fa così ___! Prendi il tuo ___.',  'Eccolo che arriva, rombando per la strada! Salta su!','Non dimenticare il tuo ___, ___!','Chi aspetta al cancello del parco con un grande sorriso?'],
  ja: ['こうえんのひ','なんてすてきないちにち！おおきくてあたたかいものがそらでかがやいています。','とっても___！___をもっていこう。','きたきた、みちをガタゴトやってくる！とびのろう！','___をわすれないで、___！','こうえんのもんでにこにこまっているのはだれ？'],
  la: ['Dies in horto','Quam pulcher dies! Magna calida res in caelo fulget.','Tam ___ est! ___ cape.',  'Ecce venit, per viam strepens! Insili!','Noli oblivisci ___, ___!','Quis ad portam horti magno risu exspectat?'],
  nl: ['Parkdag','Wat een mooie dag! Het grote warme ding schijnt aan de hemel.','Het is zo ___! Pak je ___.',  'Daar komt het, rommelend over de weg! Spring erop!','Vergeet je ___ niet, ___!','Wie wacht er bij het parkhek met een brede glimlach?'],
  pl: ['Dzień w parku','Co za piękny dzień! Wielka ciepła rzecz świeci na niebie.','Jest tak ___! Weź swój ___.',  'Nadjeżdża, dudniąc po drodze! Wskakuj!','Nie zapomnij ___, ___!','Kto czeka przy bramie parku z szerokim uśmiechem?'],
  pt: ['Dia no parque','Que dia lindo! A coisa grande e quente brilha no céu.','Está tão ___! Pegue seu ___.',  'Lá vem, rugindo pela rua! Pule!','Não esqueça seu ___, ___!','Quem está esperando no portão do parque com um grande sorriso?'],
  tr: ['Park Günü','Ne güzel bir gün! Büyük sıcak şey gökyüzünde parlıyor.','Çok ___! ___\\\'ını al.',  'İşte geliyor, yolda gümbürdeye gümbürdeye! Atla!','___\\\'ını unutma, ___!','Park kapısında kocaman gülümseyerek kim bekliyor?'],
  zh: ['公园日','多么美好的一天！大大的暖暖的东西在天上闪耀。','好___啊！拿上你的___。','来了来了，轰隆隆沿着路开来！跳上去！','别忘了你的___，___！','谁在公园门口笑着等你？'],
};

// Story 16: rainyMorning
S['rainyMorning'] = {
  ar: ['صباح ممطر','تك تك! ستحتاج شيئاً على رأسك اليوم.','اسكب بعض الشاي الدافئ في ___. إنه ___.','من يقرأ الجريدة على الطاولة؟','انظر! ___ يخرج — الجو يصبح ___!','الشيء الكبير الذي يأخذك للمدرسة يتراشق في البرك!'],
  da: ['Regnfuld morgen','Pitter patter! Du får brug for noget på hovedet i dag.','Hæld noget varm te i din ___. Det er ___.','Hvem læser avisen ved bordet?','Se! ___ kommer frem — det bliver ___!','Den store ting der kører dig til skole splasher gennem vandpytter!'],
  de: ['Regnerischer Morgen','Plitsch platsch! Du brauchst heute etwas auf dem Kopf.','Gieß warmen Tee in deine ___. Es ist ___.','Wer liest die Zeitung am Tisch?','Schau! Die ___ kommt heraus — es wird ___!','Das große Ding das dich zur Schule bringt platscht durch Pfützen!'],
  es: ['Mañana lluviosa','¡Plic plac! Hoy necesitarás algo en la cabeza.','Sirve té caliente en tu ___. Está ___.','¿Quién está leyendo el periódico en la mesa?','¡Mira! El ___ está saliendo — ¡se está poniendo ___!','¡La cosa grande que te lleva al colegio chapotea por los charcos!'],
  fr: ['Matin pluvieux','Plic ploc ! Tu auras besoin de quelque chose sur la tête aujourd\\\'hui.','Verse du thé chaud dans ton ___. C\\\'est ___.','Qui lit le journal à table ?','Regarde ! Le ___ sort — ça devient ___ !','La grande chose qui t\\\'emmène à l\\\'école éclabousse les flaques !'],
  it: ['Mattino piovoso','Plic ploc! Oggi avrai bisogno di qualcosa sulla testa.','Versa del tè caldo nella tua ___. È ___.','Chi sta leggendo il giornale al tavolo?','Guarda! Il ___ sta uscendo — sta diventando ___!','La cosa grande che ti porta a scuola spruzza attraverso le pozzanghere!'],
  ja: ['あめのあさ','ポツポツ！きょうはあたまになにかかぶらないとね。','あたたかいおちゃを___にそそいで。___だね。','テーブルでしんぶんをよんでいるのはだれ？','みて！___がでてきた — ___になってきた！','がっこうにつれていってくれるおおきなものがみずたまりをバシャバシャ！'],
  la: ['Mane pluvium','Guttae cadunt! Hodie aliquid in capite opus erit.','Theam calidam in ___ funde. ___ est.','Quis ad mensam diurna legit?','Ecce! ___ apparet — ___ fit!','Magna res quae te ad scholam ducit per lacunas pluit!'],
  nl: ['Regenachtige ochtend','Tiktak! Je hebt vandaag iets op je hoofd nodig.','Schenk warme thee in je ___. Het is ___.','Wie leest de krant aan tafel?','Kijk! De ___ komt tevoorschijn — het wordt ___!','Het grote ding dat je naar school brengt plonst door de plassen!'],
  pl: ['Deszczowy poranek','Kap kap! Dziś będziesz potrzebować czegoś na głowę.','Nalej ciepłej herbaty do ___. Jest ___.','Kto czyta gazetę przy stole?','Patrz! ___ wychodzi — robi się ___!','Wielka rzecz, która zabiera cię do szkoły, pluska w kałużach!'],
  pt: ['Manhã chuvosa','Tique-taque! Hoje você vai precisar de algo na cabeça.','Sirva chá quente na sua ___. Está ___.','Quem está lendo o jornal na mesa?','Olhe! O ___ está saindo — está ficando ___!','A coisa grande que te leva à escola espirra pelas poças!'],
  tr: ['Yağmurlu Sabah','Şıp şıp! Bugün başına bir şey gerekecek.','Sıcak çayı ___\\\'a dök. Çok ___.','Masada gazete okuyan kim?','Bak! ___ çıkıyor — ___ oluyor!','Seni okula götüren büyük şey su birikintilerinde sıçrıyor!'],
  zh: ['雨天早晨','滴答滴答！今天你得戴点什么在头上。','把热茶倒进你的___。好___。','谁在桌旁读报纸？','看！___出来了——变___了！','送你去学校的大东西在水坑里哗啦哗啦！'],
};

// ── PLACEHOLDER: More stories will be added below ──

// ══════════════════════════════════════════════════════════════════════
// Application logic — DO NOT INSERT DATA BELOW THIS LINE
// ══════════════════════════════════════════════════════════════════════
function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function applyTranslations() {
  const stories = Object.keys(S);
  if (stories.length === 0) {
    console.log('No translation data loaded yet.');
    return;
  }

  let totalReplacements = 0;

  for (const loc of LOCALES) {
    const filePath = path.join(LOCALES_DIR, loc, 'index.ts');
    let content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n');
    let locReplacements = 0;

    for (const storyKey of stories) {
      const data = S[storyKey];
      if (!data[loc]) continue;
      const vals = data[loc];

      let inStory = false;
      let depth = 0;
      const storyRe = new RegExp('^\\s+' + storyKey + ':\\s*\\{');

      for (let li = 0; li < lines.length; li++) {
        if (!inStory && storyRe.test(lines[li])) {
          inStory = true;
          depth = 0;
        }
        if (!inStory) continue;

        for (const ch of lines[li]) {
          if (ch === '{') depth++;
          if (ch === '}') depth--;
        }

        for (let fi = 0; fi < FIELDS.length; fi++) {
          if (!vals[fi]) continue;
          const fRe = new RegExp("^(\\s+" + FIELDS[fi] + ":\\s*)'(?:[^'\\\\]|\\\\.)*'(,?)\\s*$");
          const m = lines[li].match(fRe);
          if (m) {
            lines[li] = m[1] + "'" + esc(vals[fi]) + "'" + m[2];
            locReplacements++;
          }
        }

        if (depth <= 0) inStory = false;
      }
    }

    if (locReplacements > 0) {
      fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
      totalReplacements += locReplacements;
      console.log('  ' + LANG[loc] + ': ' + locReplacements + ' fields translated');
    }
  }

  console.log('\nTotal: ' + totalReplacements + ' translations applied');
}

applyTranslations();
