/**
 * LocalMusicAssetRegistry
 *
 * Registry for locally bundled music assets: instruments and note samples.
 * All music assets are local on-device -CMS metadata only references stable asset IDs.
 *
 * Supported instruments: flute, recorder, ocarina, trumpet, clarinet, saxophone
 *
 * Asset directory structure:
 *   assets/music/instruments/{instrumentId}.webp       -square thumbnail for carousels
 *   assets/music/instruments/medallions/{instrumentId}.webp -picker medallion: sky, rim and instrument
 *   assets/music/instruments/{instrumentId}-body.webp  -landscape body art the note buttons sit on
 *   assets/music/notes/{instrumentFamily}/{note}.wav   -individual note samples
 *
 * Success melodies are played back note-by-note using the instrument's own samples
 * after a music challenge is completed -no pre-recorded song files needed.
 *
 * Stories configure which instrument to use via:
 *   - CMS metadata: page.musicChallenge.instrumentId (e.g., "flute")
 *   - Local bundled stories: same field in data/bundled-stories.ts page definitions
 *
 * See MUSIC_FEATURE.md for full documentation.
 */

import { Logger } from '@/utils/logger';

const log = Logger.create('MusicAssetRegistry');

// Note names that can be part of a sequence
export type NoteName = 'C' | 'D' | 'E' | 'F' | 'G' | 'A' | 'B';

// Instrument family (the physical instrument type)
export type InstrumentFamily = 'flute' | 'recorder' | 'ocarina' | 'trumpet' | 'clarinet' | 'saxophone';

// Instrument definition with visual + audio assets
export interface InstrumentDefinition {
  id: string; // Stable ID referenced by CMS/stories (e.g., "flute", "trumpet")
  family: InstrumentFamily; // Instrument family -maps to note sample folder
  displayName: string; // Child-friendly display name
  description: string; // Short description for tooltips / accessibility
  image: number; // require() result for local instrument image
  artwork?: InstrumentArtwork; // Landscape body illustration the note buttons sit on
  medallion: number; // require() result for the picker medallion
  notes: Record<string, number>; // noteName -> require() result for note audio sample
  noteLayout: NoteLayoutItem[]; // Visual layout for on-screen note buttons
  noteCount: number; // Number of playable notes (for UI layout decisions)
}

// Landscape illustration of the instrument body; hole positions live on the note layout
export interface InstrumentArtwork {
  image: number; // require() result for the body illustration
  aspectRatio: number; // width / height of the illustration
  holeDiameter: number; // hole diameter as a fraction of the illustration width
  bell?: InstrumentBell; // Open end that swells while a note sounds (mouth-blown instruments only)
}

// Rectangle within the body illustration, as fractions of its width / height
export interface ArtworkFrame {
  x: number;
  y: number;
  width: number;
  height: number;
}

// Cutout of the body illustration around the bell / open end, scaled about `origin`
// (the join with the tube) by `scale` while a note sounds. Generated by
// scripts/make-instrument-bells.py, which owns the matching frame numbers.
export interface InstrumentBell {
  image: number; // require() result for the feathered cutout
  frame: ArtworkFrame; // where the cutout sits on the body illustration
  origin: HolePosition; // point that stays fixed while the bell expands
  scale: { x: number; y: number }; // expanded size while a note sounds
}

// Hole centre as fractions of the artwork width / height
export interface HolePosition {
  x: number;
  y: number;
}

// One colour per note on every instrument, rising through the rainbow from C (Boomwhacker order)
export const NOTE_COLORS = {
  C: '#E04E3A',
  D: '#F07A1D',
  E: '#D69A16',
  F: '#43A047',
  G: '#1E88E5',
  A: '#8E5BD8',
} as const;

// Visual layout for a single note button
export interface NoteLayoutItem {
  note: string;
  label: string; // Display label (emoji/icon for children, not music notation)
  color: string; // Button background color
  icon?: string; // Optional icon identifier for themed rendering
  hole?: HolePosition; // Where the button sits on the instrument artwork
}



// ============================================================================
// INSTRUMENT REGISTRY
//
// Each instrument has a unique child-friendly theme with colored icon buttons.
// Audio/image require() calls are commented out until real asset files are added.
// To activate an instrument: add the asset files, then uncomment the require() lines.
//
// Asset placement:
//   Image:  assets/music/instruments/{id}.png
//   Notes:  assets/music/notes/{family}/C.mp3, D.mp3, etc.
// ============================================================================

const INSTRUMENTS: Record<string, InstrumentDefinition> = {
  flute: {
    id: 'flute',
    family: 'flute',
    displayName: 'Magic Flute',
    description: 'A gentle flute with a light, airy sound',
    image: require('@/assets/music/instruments/flute.webp'),
    artwork: {
      image: require('@/assets/music/instruments/flute-body.webp'),
      aspectRatio: 8.3585,
      holeDiameter: 0.0406,
      bell: {
        image: require('@/assets/music/instruments/flute-bell.webp'),
        frame: { x: 0.78, y: 0, width: 0.22, height: 1 },
        origin: { x: 0.805, y: 0.497 },
        scale: { x: 1.02, y: 1.04 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/flute.webp'),
    notes: {
      C: require('@/assets/music/notes/flute/C.wav'),
      D: require('@/assets/music/notes/flute/D.wav'),
      E: require('@/assets/music/notes/flute/E.wav'),
      F: require('@/assets/music/notes/flute/F.wav'),
      G: require('@/assets/music/notes/flute/G.wav'),
      A: require('@/assets/music/notes/flute/A.wav'),
    },
    noteCount: 6,
    noteLayout: [
      { note: 'C', label: '⭐', color: NOTE_COLORS.C, icon: 'star', hole: { x: 0.1618, y: 0.4906 } },
      { note: 'D', label: '🌙', color: NOTE_COLORS.D, icon: 'moon', hole: { x: 0.2739, y: 0.4906 } },
      { note: 'E', label: '🍃', color: NOTE_COLORS.E, icon: 'leaf', hole: { x: 0.3853, y: 0.4906 } },
      { note: 'F', label: '🌸', color: NOTE_COLORS.F, icon: 'flower', hole: { x: 0.4951, y: 0.4906 } },
      { note: 'G', label: '☀️', color: NOTE_COLORS.G, icon: 'sun', hole: { x: 0.605, y: 0.4906 } },
      { note: 'A', label: '💧', color: NOTE_COLORS.A, icon: 'droplet', hole: { x: 0.7133, y: 0.4906 } },
    ],
  },

  recorder: {
    id: 'recorder',
    family: 'recorder',
    displayName: 'Woodland Recorder',
    description: 'A warm recorder with a soft, woody tone',
    image: require('@/assets/music/instruments/recorder.webp'),
    artwork: {
      image: require('@/assets/music/instruments/recorder-body.webp'),
      aspectRatio: 4.0728,
      holeDiameter: 0.0378,
      bell: {
        image: require('@/assets/music/instruments/recorder-bell.webp'),
        frame: { x: 0.79, y: 0, width: 0.21, height: 1 },
        origin: { x: 0.815, y: 0.5 },
        scale: { x: 1.04, y: 1.07 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/recorder.webp'),
    notes: {
      C: require('@/assets/music/notes/recorder/C.wav'),
      D: require('@/assets/music/notes/recorder/D.wav'),
      E: require('@/assets/music/notes/recorder/E.wav'),
      F: require('@/assets/music/notes/recorder/F.wav'),
      G: require('@/assets/music/notes/recorder/G.wav'),
      A: require('@/assets/music/notes/recorder/A.wav'),
    },
    noteCount: 6,
    noteLayout: [
      { note: 'C', label: '🌲', color: NOTE_COLORS.C, icon: 'tree', hole: { x: 0.1429, y: 0.4906 } },
      { note: 'D', label: '🍄', color: NOTE_COLORS.D, icon: 'mushroom', hole: { x: 0.2348, y: 0.4927 } },
      { note: 'E', label: '🦋', color: NOTE_COLORS.E, icon: 'butterfly', hole: { x: 0.3277, y: 0.4906 } },
      { note: 'F', label: '🐦', color: NOTE_COLORS.F, icon: 'bird', hole: { x: 0.4206, y: 0.4906 } },
      { note: 'G', label: '🌻', color: NOTE_COLORS.G, icon: 'sunflower', hole: { x: 0.5135, y: 0.4948 } },
      { note: 'A', label: '🦊', color: NOTE_COLORS.A, icon: 'fox', hole: { x: 0.6085, y: 0.4927 } },
    ],
  },

  ocarina: {
    id: 'ocarina',
    family: 'ocarina',
    displayName: 'Enchanted Ocarina',
    description: 'A mysterious ocarina with a dreamy, magical sound',
    image: require('@/assets/music/instruments/ocarina.webp'),
    artwork: {
      image: require('@/assets/music/instruments/ocarina-body.webp'),
      aspectRatio: 1.7865,
      holeDiameter: 0.0581,
      bell: {
        image: require('@/assets/music/instruments/ocarina-bell.webp'),
        frame: { x: 0.72, y: 0, width: 0.24, height: 0.34 },
        origin: { x: 0.83, y: 0.3 },
        scale: { x: 1.03, y: 1.05 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/ocarina.webp'),
    notes: {
      C: require('@/assets/music/notes/ocarina/C.wav'),
      D: require('@/assets/music/notes/ocarina/D.wav'),
      E: require('@/assets/music/notes/ocarina/E.wav'),
      F: require('@/assets/music/notes/ocarina/F.wav'),
      G: require('@/assets/music/notes/ocarina/G.wav'),
      A: require('@/assets/music/notes/ocarina/A.wav'),
    },
    noteCount: 6,
    noteLayout: [
      { note: 'C', label: '🔮', color: NOTE_COLORS.C, icon: 'crystal', hole: { x: 0.1668, y: 0.6622 } },
      { note: 'D', label: '✨', color: NOTE_COLORS.D, icon: 'sparkle', hole: { x: 0.2984, y: 0.6683 } },
      { note: 'E', label: '🌟', color: NOTE_COLORS.E, icon: 'glow', hole: { x: 0.4315, y: 0.6707 } },
      { note: 'F', label: '🦉', color: NOTE_COLORS.F, icon: 'owl', hole: { x: 0.5685, y: 0.6719 } },
      { note: 'G', label: '🌌', color: NOTE_COLORS.G, icon: 'galaxy', hole: { x: 0.707, y: 0.6719 } },
      { note: 'A', label: '☄️', color: NOTE_COLORS.A, icon: 'comet', hole: { x: 0.8406, y: 0.6659 } },
    ],
  },

  trumpet: {
    id: 'trumpet',
    family: 'trumpet',
    displayName: 'Golden Trumpet',
    description: 'A bright trumpet with a bold, heroic sound',
    image: require('@/assets/music/instruments/trumpet.webp'),
    artwork: {
      image: require('@/assets/music/instruments/trumpet-body.webp'),
      aspectRatio: 3.1345,
      holeDiameter: 0.081,
      bell: {
        image: require('@/assets/music/instruments/trumpet-bell.webp'),
        frame: { x: 0.735, y: 0, width: 0.265, height: 1 },
        origin: { x: 0.76, y: 0.5 },
        scale: { x: 1.04, y: 1.07 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/trumpet.webp'),
    notes: {
      C: require('@/assets/music/notes/trumpet/C.wav'),
      D: require('@/assets/music/notes/trumpet/D.wav'),
      E: require('@/assets/music/notes/trumpet/E.wav'),
    },
    noteCount: 3,
    noteLayout: [
      { note: 'C', label: '🛡️', color: NOTE_COLORS.C, icon: 'shield', hole: { x: 0.193, y: 0.437 } },
      { note: 'D', label: '⚔️', color: NOTE_COLORS.D, icon: 'sword', hole: { x: 0.3314, y: 0.437 } },
      { note: 'E', label: '👑', color: NOTE_COLORS.E, icon: 'crown', hole: { x: 0.4697, y: 0.437 } },
    ],
  },

  clarinet: {
    id: 'clarinet',
    family: 'clarinet',
    displayName: 'Jazzy Clarinet',
    description: 'A smooth clarinet with a rich, jazzy tone',
    image: require('@/assets/music/instruments/clarinet.webp'),
    artwork: {
      image: require('@/assets/music/instruments/clarinet-body.webp'),
      aspectRatio: 3.966,
      holeDiameter: 0.0368,
      bell: {
        image: require('@/assets/music/instruments/clarinet-bell.webp'),
        frame: { x: 0.79, y: 0, width: 0.21, height: 1 },
        origin: { x: 0.815, y: 0.5 },
        scale: { x: 1.04, y: 1.07 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/clarinet.webp'),
    notes: {
      C: require('@/assets/music/notes/clarinet/C.wav'),
      D: require('@/assets/music/notes/clarinet/D.wav'),
      E: require('@/assets/music/notes/clarinet/E.wav'),
      F: require('@/assets/music/notes/clarinet/F.wav'),
      G: require('@/assets/music/notes/clarinet/G.wav'),
      A: require('@/assets/music/notes/clarinet/A.wav'),
    },
    noteCount: 6,
    noteLayout: [
      { note: 'C', label: '🎩', color: NOTE_COLORS.C, icon: 'hat', hole: { x: 0.1777, y: 0.5008 } },
      { note: 'D', label: '🎷', color: NOTE_COLORS.D, icon: 'sax', hole: { x: 0.2773, y: 0.5007 } },
      { note: 'E', label: '🌃', color: NOTE_COLORS.E, icon: 'city', hole: { x: 0.3761, y: 0.5007 } },
      { note: 'F', label: '🎭', color: NOTE_COLORS.F, icon: 'mask', hole: { x: 0.4725, y: 0.501 } },
      { note: 'G', label: '🎪', color: NOTE_COLORS.G, icon: 'tent', hole: { x: 0.5633, y: 0.5014 } },
      { note: 'A', label: '🎺', color: NOTE_COLORS.A, icon: 'trumpet', hole: { x: 0.6566, y: 0.5016 } },
    ],
  },

  saxophone: {
    id: 'saxophone',
    family: 'saxophone',
    displayName: 'Sunshine Saxophone',
    description: 'A funky saxophone with a warm, soulful sound',
    image: require('@/assets/music/instruments/saxophone.webp'),
    artwork: {
      image: require('@/assets/music/instruments/saxophone-body.webp'),
      aspectRatio: 2.7932,
      holeDiameter: 0.04,
      bell: {
        image: require('@/assets/music/instruments/saxophone-bell.webp'),
        frame: { x: 0.68, y: 0, width: 0.32, height: 1 },
        origin: { x: 0.71, y: 0.565 },
        scale: { x: 1.04, y: 1.07 },
      },
    },
    medallion: require('@/assets/music/instruments/medallions/saxophone.webp'),
    notes: {
      C: require('@/assets/music/notes/saxophone/C.wav'),
      D: require('@/assets/music/notes/saxophone/D.wav'),
      E: require('@/assets/music/notes/saxophone/E.wav'),
      F: require('@/assets/music/notes/saxophone/F.wav'),
      G: require('@/assets/music/notes/saxophone/G.wav'),
    },
    noteCount: 5,
    noteLayout: [
      { note: 'C', label: '🌈', color: NOTE_COLORS.C, icon: 'rainbow', hole: { x: 0.074, y: 0.5627 } },
      { note: 'D', label: '🎸', color: NOTE_COLORS.D, icon: 'guitar', hole: { x: 0.1687, y: 0.5627 } },
      { note: 'E', label: '🥁', color: NOTE_COLORS.E, icon: 'drum', hole: { x: 0.2633, y: 0.5593 } },
      { note: 'F', label: '🎤', color: NOTE_COLORS.F, icon: 'mic', hole: { x: 0.3574, y: 0.561 } },
      { note: 'G', label: '💃', color: NOTE_COLORS.G, icon: 'dance', hole: { x: 0.4521, y: 0.561 } },
    ],
  },
};



// Backward compatibility aliases (old ID → new ID)
// The original implementation used "flute_basic" -now simplified to "flute".
const INSTRUMENT_ALIASES: Record<string, string> = {
  flute_basic: 'flute',
  recorder_basic: 'recorder',
  ocarina_basic: 'ocarina',
  trumpet_basic: 'trumpet',
  clarinet_basic: 'clarinet',
  saxophone_basic: 'saxophone',
};

/**
 * Get an instrument definition by ID.
 * Supports backward-compatible aliases (e.g., "flute_basic" → "flute").
 * Returns undefined if the instrument is not registered.
 */
export function getInstrument(instrumentId: string): InstrumentDefinition | undefined {
  // Try direct lookup first, then alias
  const resolvedId = INSTRUMENTS[instrumentId] ? instrumentId : (INSTRUMENT_ALIASES[instrumentId] ?? instrumentId);
  const instrument = INSTRUMENTS[resolvedId];
  if (!instrument) {
    log.warn(`Instrument not found: ${instrumentId}`);
  }
  return instrument;
}

/**
 * Get all instruments belonging to a specific family.
 */
export function getInstrumentsByFamily(family: InstrumentFamily): InstrumentDefinition[] {
  return Object.values(INSTRUMENTS).filter(i => i.family === family);
}

/**
 * Validate that all assets referenced by a music challenge config exist locally.
 * Returns a list of missing asset IDs (empty = all valid).
 *
 * Note: Only validates instrument and note assets. Success songs are no longer
 * pre-recorded -the app plays back the requiredSequence note-by-note using the
 * instrument's own samples after challenge completion.
 */
export function validateMusicChallengeAssets(
  instrumentId: string,
  requiredSequence: string[],
): string[] {
  const missing: string[] = [];

  const resolvedId = INSTRUMENTS[instrumentId] ? instrumentId : (INSTRUMENT_ALIASES[instrumentId] ?? instrumentId);
  const instrument = INSTRUMENTS[resolvedId];
  if (!instrument) {
    missing.push(`instrument:${instrumentId}`);
  } else {
    // Check that all required notes exist
    for (const note of requiredSequence) {
      if (!(note in instrument.notes) || !instrument.notes[note]) {
        missing.push(`note:${instrumentId}/${note}`);
      }
    }
  }

  if (missing.length > 0) {
    log.error(`Missing music assets: ${missing.join(', ')}`);
  }

  return missing;
}

/**
 * Get all registered instrument IDs.
 */
export function getAvailableInstrumentIds(): string[] {
  return Object.keys(INSTRUMENTS);
}

/**
 * Register a new instrument at runtime (for testing or dynamic loading).
 */
export function registerInstrument(instrument: InstrumentDefinition): void {
  INSTRUMENTS[instrument.id] = instrument;
  log.debug(`Registered instrument: ${instrument.id}`);
}

// ============================================================================
// PRACTICE SONG LIBRARY
//
// Songs for Practise mode -defined as note sequences only (no pre-recorded audio).
// Each song specifies which notes to play; the instrument samples provide the sound.
// Songs are instrument-agnostic: any instrument can play them as long as it has the
// required notes. The UI filters songs by the selected instrument's available notes.
// ============================================================================

export type PracticeSongDifficulty = 'easy' | 'medium' | 'hard';
export type PracticeSongCategory = 'nursery' | 'storybook' | 'forces';

export interface PracticeSong {
  id: string;
  nameKey: string;             // i18n key under music.songs.*
  difficulty: PracticeSongDifficulty;
  category: PracticeSongCategory;
  /** The note sequence to play (e.g. ['C','D','E','D','C']) */
  sequence: string[];
  /** Notes used in this song (derived, but stored for quick filtering) */
  requiredNotes: string[];
  /** Tempo hint in BPM (used for preview playback speed) */
  bpm?: number;
  /** Duration of each sequence entry in beats; omitted songs play every entry for one beat */
  rhythm?: number[];
}

const PRACTICE_SONGS: PracticeSong[] = [
  // =====================================================================
  // NURSERY RHYMES -IP-free / public domain melodies
  // =====================================================================

  // ---- Easy nursery rhymes ----
  {
    id: 'hot_cross_buns',
    nameKey: 'music.songs.hotCrossBuns',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['E', 'D', 'C', 'E', 'D', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E'],
    bpm: 100,
    rhythm: [1, 1, 2, 1, 1, 2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 2],
  },
  {
    id: 'rain_rain',
    nameKey: 'music.songs.rainRain',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['E', 'E', 'C', 'E', 'E', 'C', 'E', 'F', 'E', 'D', 'C', 'D', 'E'],
    requiredNotes: ['C', 'D', 'E', 'F'],
    bpm: 95,
  },
  {
    id: 'au_clair_lune',
    nameKey: 'music.songs.auClairLune',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['C', 'C', 'C', 'D', 'E', 'D', 'C', 'E', 'D', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E'],
    bpm: 90,
    rhythm: [1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 4],
  },
  {
    id: 'mary_lamb',
    nameKey: 'music.songs.maryLamb',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['E', 'D', 'C', 'D', 'E', 'E', 'E', 'D', 'D', 'D', 'E', 'G', 'G'],
    requiredNotes: ['C', 'D', 'E', 'G'],
    bpm: 110,
    rhythm: [1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2],
  },
  {
    id: 'itsy_bitsy_spider',
    nameKey: 'music.songs.itsyBitsySpider',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['G', 'C', 'C', 'C', 'D', 'E', 'E', 'D', 'C', 'D', 'E', 'C'],
    requiredNotes: ['C', 'D', 'E', 'G'],
    bpm: 100,
    rhythm: [0.5, 1, 0.5, 1, 0.5, 1.5, 1, 0.5, 1, 0.5, 1, 2],
  },
  {
    id: 'row_row_boat',
    nameKey: 'music.songs.rowRowBoat',
    difficulty: 'easy',
    category: 'nursery',
    sequence: ['C', 'C', 'C', 'D', 'E', 'E', 'D', 'E', 'F', 'G'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 85,
    rhythm: [1, 1, 0.75, 0.25, 1, 0.75, 0.25, 0.75, 0.25, 2],
  },

  // ---- Medium nursery rhymes ----
  {
    id: 'twinkle_star',
    nameKey: 'music.songs.twinkleStar',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['C', 'C', 'G', 'G', 'A', 'A', 'G', 'F', 'F', 'E', 'E', 'D', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G', 'A'],
    bpm: 100,
    rhythm: [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2],
  },
  {
    id: 'ode_to_joy',
    nameKey: 'music.songs.odeToJoy',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['E', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'C', 'D', 'E', 'E', 'D', 'D'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 108,
    rhythm: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, 0.5, 2],
  },
  {
    id: 'london_bridge',
    nameKey: 'music.songs.londonBridge',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['G', 'A', 'G', 'F', 'E', 'F', 'G', 'D', 'E', 'F', 'E', 'F', 'G'],
    requiredNotes: ['D', 'E', 'F', 'G', 'A'],
    bpm: 112,
    rhythm: [1.5, 0.5, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2],
  },
  {
    id: 'three_blind_mice',
    nameKey: 'music.songs.threeBlindMice',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['E', 'D', 'C', 'E', 'D', 'C', 'G', 'F', 'F', 'E', 'G', 'F', 'F', 'E'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 105,
    rhythm: [1, 1, 2, 1, 1, 2, 1, 0.5, 0.5, 2, 1, 0.5, 0.5, 2],
  },
  {
    id: 'humpty_dumpty',
    nameKey: 'music.songs.humptyDumpty',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['C', 'E', 'G', 'G', 'E', 'C', 'D', 'E', 'F', 'E', 'D'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 90,
  },
  {
    id: 'jack_and_jill',
    nameKey: 'music.songs.jackAndJill',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['C', 'D', 'E', 'F', 'G', 'G', 'G', 'G', 'F', 'E', 'F', 'G', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 105,
  },
  {
    id: 'old_macdonald',
    nameKey: 'music.songs.oldMacdonald',
    difficulty: 'medium',
    category: 'nursery',
    sequence: ['C', 'C', 'C', 'G', 'A', 'A', 'G', 'E', 'E', 'D', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'G', 'A'],
    bpm: 110,
    rhythm: [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2],
  },

  // ---- Hard nursery rhymes ----
  {
    id: 'jingle_bells',
    nameKey: 'music.songs.jingleBells',
    difficulty: 'hard',
    category: 'nursery',
    sequence: ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'D', 'E', 'F', 'F', 'F', 'F', 'F', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'D', 'G'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 120,
    rhythm: [1, 1, 2, 1, 1, 2, 1, 1, 1.5, 0.5, 4, 1, 1, 1.5, 0.5, 1, 1, 0.5, 0.5, 1, 1, 1, 1, 2, 2],
  },
  {
    id: 'frere_jacques',
    nameKey: 'music.songs.frereJacques',
    difficulty: 'hard',
    category: 'nursery',
    sequence: ['C', 'D', 'E', 'C', 'C', 'D', 'E', 'C', 'E', 'F', 'G', 'E', 'F', 'G', 'G', 'A', 'G', 'F', 'E', 'C', 'G', 'A', 'G', 'F', 'E', 'C', 'C', 'G', 'C', 'C', 'G', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G', 'A'],
    bpm: 120,
    rhythm: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0.5, 0.5, 0.5, 0.5, 1, 1, 0.5, 0.5, 0.5, 0.5, 1, 1, 1, 1, 2, 1, 1, 2],
  },
  {
    id: 'happy_birthday',
    nameKey: 'music.songs.happyBirthday',
    difficulty: 'hard',
    category: 'nursery',
    sequence: ['C', 'C', 'D', 'C', 'F', 'E', 'C', 'C', 'D', 'C', 'G', 'F', 'C', 'C', 'C', 'A', 'F', 'E', 'D'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G', 'A'],
    bpm: 100,
    rhythm: [0.75, 0.25, 1, 1, 1, 2, 0.75, 0.25, 1, 1, 1, 2, 0.75, 0.25, 1, 1, 1, 1, 1],
  },
  {
    id: 'hickory_dickory',
    nameKey: 'music.songs.hickoryDickory',
    difficulty: 'hard',
    category: 'nursery',
    sequence: ['G', 'A', 'G', 'E', 'C', 'G', 'A', 'G', 'E', 'C', 'D', 'E', 'E', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'G', 'A'],
    bpm: 115,
  },

  // =====================================================================
  // STORYBOOK SONGS -Original compositions for storybook instrument play
  // =====================================================================

  // ---- Easy storybook songs ----
  {
    id: 'raindrop_song',
    nameKey: 'music.songs.raindropSong',
    difficulty: 'easy',
    category: 'storybook',
    sequence: ['E', 'E', 'D', 'D', 'C', 'C', 'D', 'E', 'E', 'D', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E'],
    bpm: 110,
  },
  {
    id: 'dreamtime_lullaby',
    nameKey: 'music.songs.dreamtimeLullaby',
    difficulty: 'easy',
    category: 'storybook',
    sequence: ['E', 'D', 'C', 'D', 'E', 'D', 'C', 'E', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E'],
    bpm: 70,
  },
  {
    id: 'ocean_waves',
    nameKey: 'music.songs.oceanWaves',
    difficulty: 'easy',
    category: 'storybook',
    sequence: ['C', 'D', 'E', 'F', 'E', 'D', 'C', 'D', 'E', 'F', 'E', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F'],
    bpm: 80,
  },

  // ---- Medium storybook songs ----
  {
    id: 'forest_wander',
    nameKey: 'music.songs.forestWander',
    difficulty: 'medium',
    category: 'storybook',
    sequence: ['C', 'E', 'G', 'E', 'C', 'E', 'G', 'E', 'D', 'F', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 90,
  },
  {
    id: 'starlight_dance',
    nameKey: 'music.songs.starlightDance',
    difficulty: 'medium',
    category: 'storybook',
    sequence: ['G', 'E', 'G', 'E', 'F', 'D', 'F', 'D', 'E', 'C', 'E', 'G', 'F', 'E', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 100,
  },
  {
    id: 'mountain_echo',
    nameKey: 'music.songs.mountainEcho',
    difficulty: 'medium',
    category: 'storybook',
    sequence: ['C', 'D', 'E', 'F', 'G', 'G', 'F', 'E', 'D', 'C', 'E', 'G', 'E', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 95,
  },
  {
    id: 'butterfly_flight',
    nameKey: 'music.songs.butterflyFlight',
    difficulty: 'medium',
    category: 'storybook',
    sequence: ['E', 'G', 'F', 'E', 'D', 'F', 'E', 'D', 'C', 'E', 'D', 'C', 'D', 'E', 'F', 'G'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 105,
  },
  {
    id: 'moonbeam_waltz',
    nameKey: 'music.songs.moonbeamWaltz',
    difficulty: 'medium',
    category: 'storybook',
    sequence: ['C', 'E', 'G', 'F', 'D', 'F', 'E', 'C', 'E', 'D', 'C', 'D', 'E', 'G', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 85,
  },

  // ---- Hard storybook songs ----
  {
    id: 'sunrise_march',
    nameKey: 'music.songs.sunriseMarch',
    difficulty: 'hard',
    category: 'storybook',
    sequence: ['C', 'C', 'D', 'E', 'E', 'F', 'G', 'G', 'A', 'G', 'F', 'E', 'D', 'C', 'D', 'E', 'F', 'G', 'A'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G', 'A'],
    bpm: 100,
  },
  {
    id: 'river_journey',
    nameKey: 'music.songs.riverJourney',
    difficulty: 'hard',
    category: 'storybook',
    sequence: ['C', 'D', 'E', 'G', 'F', 'E', 'D', 'C', 'D', 'F', 'E', 'G', 'F', 'E', 'D', 'E', 'F', 'G', 'E', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 95,
  },

  // =====================================================================
  // FORCES SONGS -Slow, smooth melodies representing physical forces
  // Used in storybooks to teach push, pull, lift, lower, break, and fix.
  // =====================================================================
  {
    id: 'song_of_push',
    nameKey: 'music.songs.songOfPush',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['C', 'D', 'E', 'F', 'G', 'F', 'E', 'G'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 70,
  },
  {
    id: 'song_of_pull',
    nameKey: 'music.songs.songOfPull',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['G', 'F', 'E', 'D', 'C', 'D', 'E', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 70,
  },
  {
    id: 'song_of_lift',
    nameKey: 'music.songs.songOfLift',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['C', 'E', 'G', 'E', 'C', 'E', 'F', 'G'],
    requiredNotes: ['C', 'E', 'F', 'G'],
    bpm: 70,
  },
  {
    id: 'song_of_lower',
    nameKey: 'music.songs.songOfLower',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['G', 'E', 'C', 'E', 'G', 'F', 'D', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 70,
  },
  {
    id: 'song_of_break',
    nameKey: 'music.songs.songOfBreak',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['G', 'C', 'F', 'D', 'E', 'C', 'G', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F', 'G'],
    bpm: 70,
  },
  {
    id: 'song_of_fix',
    nameKey: 'music.songs.songOfFix',
    difficulty: 'easy',
    category: 'forces',
    sequence: ['C', 'D', 'E', 'F', 'E', 'D', 'E', 'C'],
    requiredNotes: ['C', 'D', 'E', 'F'],
    bpm: 70,
  },
];

/**
 * Get all practice songs that can be played with a given instrument.
 * Filters out songs whose required notes exceed the instrument's available notes.
 */
export function getPracticeSongsForInstrument(instrumentId: string): PracticeSong[] {
  const instrument = getInstrument(instrumentId);
  if (!instrument) return [];
  const availableNotes = new Set(Object.keys(instrument.notes));
  return PRACTICE_SONGS.filter(song =>
    song.requiredNotes.every(note => availableNotes.has(note))
  );
}

/**
 * Get a specific practice song by ID.
 */
export function getPracticeSong(songId: string): PracticeSong | undefined {
  return PRACTICE_SONGS.find(s => s.id === songId);
}

/**
 * Get all practice songs.
 */
export function getAllPracticeSongs(): PracticeSong[] {
  return [...PRACTICE_SONGS];
}
