name: Func Tests build and push

on:
  push:
    paths:
      - 'func-tests/**'
      - '.github/workflows/func-tests-build.yml'

env:
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

jobs:
  build-func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Func Test Image
        working-directory: func-tests
        run: |
          VERSION=$(git rev-list --count HEAD)
          docker build -t func-tests:$VERSION -t func-tests:latest .
          docker tag func-tests:$VERSION $DOCKER_REPO/func-tests:$VERSION
          docker tag func-tests:latest $DOCKER_REPO/func-tests:latest
          docker push $DOCKER_REPO/func-tests:$VERSION
          docker push $DOCKER_REPO/func-tests:latest
