name: Func Tests build and push

on:
  push:
    paths:
      - 'func-tests/**'
      - '.github/workflows/func-tests-build.yml'

env:
  DOCKER_REPO: ghcr.io/${{secrets.GHCR_USERNAME}}

jobs:
  build-func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and Push Func Test Image
        working-directory: func-tests
        run: |
          docker build -t func-tests:latest .
          docker tag func-tests:latest $GHCR_REPO/func-tests:latest
          docker push $GHCR_REPO/func-tests:latest
