# .github/workflows/gateway-service-ci.yml
name: Gateway Service CI

on:
  push:
    paths:
      - 'gateway-service/**'
      - '.github/workflows/gateway-service-ci.yml'

env:
  IMAGE_NAME: gateway-service
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Gateway Image
        working-directory: gateway-service
        run: |
          VERSION=$(git rev-list --count HEAD)
          docker build -t $DOCKER_REPO:$VERSION -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:$VERSION
          docker push $DOCKER_REPO:latest

      - name: Run Functional Tests
        run: |
          docker-compose --profile func-tests build
          docker-compose --profile func-tests up --abort-on-container-exit --exit-code-from func-tests

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: func-tests/build/reports/tests
          if-no-files-found: warn

      - name: Run NFT Tests
        run: |
          docker-compose --profile nft build
          docker-compose --profile nft up --abort-on-container-exit --exit-code-from nft

      - name: Upload Gatling HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: nft/build/reports/gatling
          if-no-files-found: warn