name: NFT Tests CI

on:
  push:
    paths:
      - 'nft/**'
      - '.github/workflows/nft-tests-ci.yml'

env:
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

jobs:
  build-nft-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push NFT Test Image
        working-directory: nft
        run: |
          docker build -t nft:latest .
          docker tag nft:latest $DOCKER_REPO/nft:latest
          docker push $DOCKER_REPO/nft:latest
